<?php
$collection = $this->getCollection();
if(!empty($collection)):
?>
<div class="col-sm-12 category-performance">
    <div class="row">
        <?php foreach ($collection as $category): ?>
            <div class="col-md-3 col-sm-6 col-xs-12 item">
                <a class="cat-container" href="<?php echo $category['link'] ?>">
                    <div class="img">
                        <img src="<?php echo $category['image'] ?>" width="200px">
                    </div>
                    <div class="name">
                        <?php echo $category['label'] ?>
                        <div class="icon"><i class="fa fa-chevron-right"></i></div>
                    </div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function(){

        jQuery('.category-performance .item img').imageFallback(['/media/category/model-watermark.png']);

    });
</script>
