<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 12/5/16
 * Time: 4:07 PM
 */

class Homebase_Finder_Block_Adminhtml_Record_Grid extends Mage_Adminhtml_Block_Widget_Grid {
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setDefaultSort('record_id');
        $this->setId('hfinder_record_grid');
        $this->setDefaultDir('asc');
        $this->setSaveParametersInSession(true);
    }
    protected function _getCollectionClass(){
        return 'hfinder/record_collection';
    }
    protected function _prepareCollection(){
        $collection = Mage::getResourceModel($this->_getCollectionClass());
        $this->setCollection($collection);
        return parent::_prepareCollection();
    }
    protected function _prepareColumns(){
        $this->addColumn('id',
            array(
                'header'=> $this->__('ID'),
                'align' =>'right',
                'width' => '10px',
                'index' => 'id'
            )
        );
        $this->addColumn('year',
            array(
                'header'=> $this->__('Year'),
                'index' => 'year'
            )
        );
        $this->addColumn('make',
            array(
                'header'=> $this->__('Make'),
                'index' => 'make'
            )
        );
        $this->addColumn('model',
            array(
                'header'=> $this->__('Model'),
                'index' => 'model'
            )
        );

        $this->addColumn('category',
            array(
                'header'=> $this->__('Category Id'),
                'index' => 'category'
            )
        );
        return parent::_prepareColumns();
    }
}