<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 2/28/17
 * Time: 11:26 PM
 */

class Homebase_Autopart_Model_Combination extends Mage_Core_Model_Abstract{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('hautopart/combination');
    }
}