<?php
class Homebase_Autopart_Model_Customer extends Mage_Core_Model_Abstract{

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('hautopart/customer');
    }

}