<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 4/11/17
 * Time: 3:00 PM
 */

class Homebase_Autopart_Model_Image extends Mage_Core_Model_Abstract{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('hautopart/image');
    }
}