<?php
/**
 * Created by PhpStorm.
 * User: olivercastro
 * Date: 12/03/2017
 * Time: 12:31 AM
 */

class Homebase_Autopart_Model_Label extends Mage_Core_Model_Abstract{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('hautopart/label');
    }
}