<?php
/**
 * Created by PhpStorm.
 * User: olivercastro
 * Date: 09/03/2017
 * Time: 7:59 PM
 */

class Homebase_Autopart_Model_Mix extends Mage_Core_Model_Abstract{

    protected $_eventPrefix = 'auto_fitment';

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('hautopart/mix');
    }

}