<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 7/4/17
 * Time: 11:29 PM
 */
?>
<style>
.head {
    padding: 10px 15px;
    font-size: 13px!important;
    font-weight: bold;
    text-transform: uppercase!important;
    border: 1px solid #215f9f!important;
    background-color: #215f9f!important;
    color: #777!important;
    position: relative;
    cursor: pointer;
    border-radius: 7px 7px 0 0;
    margin-top: 14px;
    color: white!important;
}

.category-products .block-layered-nav .block-content .content ol li label {
    font-size: 14px!important;
    padding-left: 15px;
    cursor: pointer;
    color: #337ab7!important;
}
</style>
<div class="container">
    <div class="col-md-12">
        <?php echo $this->getChildHtml('product-listing');?>
    </div>
</div>
