<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 3/6/17
 * Time: 10:12 PM
 */

class Homebase_Autopart_Block_Adminhtml_Product_Edit_Tab_Combination_Items extends Mage_Adminhtml_Block_Widget{
    public function __construct()
    {
        parent::__construct();
        $this->setTemplate('homebase/product/edit/tab/combination/items.phtml');
    }

    protected function _prepareLayout()
    {
        $this->setChild('add_button',
            $this->getLayout()->createBlock('adminhtml/widget_button')
                ->setData(array(
                    'label' => Mage::helper('catalog')->__('Add New Combination'),
                    'class' => 'add',
                    'id'    => 'add_new_defined_combination'
                ))
        );

        $this->setChild('import_button',
            $this->getLayout()->createBlock('adminhtml/widget_button')
            ->setData(array(
                'label' => Mage::helper('hautopart')->__("Import Combination File"),
                'class' => 'import',
                'id'    => 'import_defined_combination'
            ))
        );

        $this->setChild('combinations_box',
            $this->getLayout()->createBlock('hautopart/adminhtml_product_edit_tab_combination_items_entries')
        );
        parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getAddButtonHtml()
    {
        return $this->getChildHtml('add_button');
    }
    public function getImportButtonHtml(){
        return $this->getChildHtml('import_button');
    }
    public function getCombinationsBoxHtml()
    {
        return $this->getChildHtml('combinations_box');
    }
}