<?php
$listing = $this->getParts();
$ctr = 0;
$limit = $this->getLimit();
$total = $listing->count();
$title = $this->getTitle();
$titlefix = str_replace(" ","-","$title");
$lowertitle = strtolower($titlefix);

$request = $this->getRequest();
$requestString = $request->getRequestString();
$requestSegments = array_filter(explode('/', $requestString));

$blockowner = str_replace('.html','',end($requestSegments));
/** @var Homebase_Auto_Block_Category $this */
?>



<div class="row">
    <div class="col-sm-12">
        <img src="/media/category/category.jpg" alt="<?php echo $title ?>" width="100%" />
        <div class="part-listing-title">
            <h1><?php echo $this->getTitle(); ?></h1>
        </div>
    </div>

    <div class="listing-top-text">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing-top-' . $blockowner)->toHtml(); ?>
    </div>
    <div class="part-listing-container">
        <div class="col-sm-12">
            <p>Choose from these available products:</p>
            <?php foreach($listing as $item): ?>
                <?php if($ctr % $limit == 0 ): ?>
                    <ul class="col-xs-12 col-sm-3 col-md-3 parts-listing listing-group-<?php echo $ctr+1; ?>">
                <?php endif; ?>
                    <li>
                        <a href="<?php echo $item->getLink(); ?>">
                            <?php echo $item->getLabel(); ?>
                        </a>
                    </li>
                <?php if($ctr % $limit == ($limit - 1) || ($ctr+1) == $total): ?>
                    </ul>
                <?php endif; ?>
                <?php $ctr++; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="listing-bottom-text">
        <?php $bottomText = $this->getLayout()->createBlock('cms/block')->setBlockId('listing-bottom-' . $blockowner)->toHtml(); ?>
        <?php echo $bottomText; ?>
    </div>
    <?php if(empty(trim($bottomText))): ?>
        <?php echo $this->getChildHtml('default-category-content'); ?>
    <?php endif; ?>
</div>

<div id="shop-cat">
<?php echo $this->getLayout()->createBlock('hauto/home_shopby_category')->setTemplate('/hauto/home/shopby/category.phtml')->toHtml();
?>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
         jQuery('#shop-cat').detach().insertBefore('.footer-container ');
               
    });
  
</script>