<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 8/10/17
 * Time: 9:49 PM
 */

class Homebase_Sitemap_Block_Adminhtml_Multimap_Edit_Form extends Mage_Adminhtml_Block_Widget_Form{
    public function __construct()
    {
        parent::__construct();
        $this->setId('hsitemap_multimap_form');
        $this->setTitle($this->__("Multi Sitemap Information"));
    }
    protected function _prepareForm(){
        $model = Mage::registry('hsitemap_multimap');

        $_form = new Varien_Data_Form(array(
            'id'        => 'edit_form',
            'action'    => $this->getUrl('*/*/save',array('id' => $this->getRequest()->getParam('id'))),
            'method'    => 'post'
        ));

        $_fieldset = $_form->addFieldset('hsitemap_fieldset',array(
            'legend'    => Mage::helper('hsitemap')->__('Sitemap'),
            'class'     => 'fieldset-wide'
        ));

        if($model->getId()){
            $_fieldset->addField('id','hidden',array(
                'name'  => 'id',
                'value' => $model->getId()
            ));
        }

        $_fieldset->addField('filename', 'text', array(
            'label' => Mage::helper('hsitemap')->__('Filename'),
            'name'  => 'filename',
            'required' => true,
            'note'  => Mage::helper('adminhtml')->__('example: sitemap.xml'),
            'value' => $model->getFilename()

        ));

        $_fieldset->addField('path', 'text', array(
            'label' => Mage::helper('hsitemap')->__('Path'),
            'name'  => 'path',
            'required' => true,
            'note'  => Mage::helper('adminhtml')->__('example: "sitemap/" or "/" for base path (path must be writeable)'),
            'value' => $model->getPath()
        ));

        if (!Mage::app()->isSingleStoreMode()) {
            $field = $_fieldset->addField('store_id', 'select', array(
                'label'    => Mage::helper('sitemap')->__('Store View'),
                'title'    => Mage::helper('sitemap')->__('Store View'),
                'name'     => 'store_id',
                'required' => true,
                'values'   => Mage::getSingleton('adminhtml/system_store')->getStoreValuesForForm(),
            ));
            $renderer = $this->getLayout()->createBlock('adminhtml/store_switcher_form_renderer_fieldset_element');
            $field->setRenderer($renderer);
        }
        else {
            $_fieldset->addField('store_id', 'hidden', array(
                'name'     => 'store_id',
                'value'    => Mage::app()->getStore(true)->getId()
            ));
        }
        $_form->setValues($model->getData());
        $_form->setUseContainer(true);
        $this->setForm($_form);

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}