<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 4/2/17
 * Time: 7:02 PM
 */

/** @var Homebase_Autopart_Block_Display_List $this */
$list = $this->getList();
$rowCount = 0;
$flag = 0;

$subtitle = "";
if(strpos(Mage::helper('core/url')->getCurrentUrl(), '/make/') !== false) {
    $subtitle = "Pick your vehicle’s model from the selection below:";
} else if (strpos(Mage::helper('core/url')->getCurrentUrl(), '/model/') !== false) {
    $subtitle = "Please select your vehicle's year below:";
} else if (strpos(Mage::helper('core/url')->getCurrentUrl(), '/year/') !== false) {
    $subtitle = "Here are the available accessories for your vehicle:";
}

$request = $this->getRequest();
$requestString = $request->getRequestString();
$requestSegments = array_filter(explode('/', $requestString));

$blockowner = str_replace('.html','',end($requestSegments));

$titlePrefix = "";
if($request->getActionName() == 'model') {
    $titlePrefix = '&nbsp;Parts & Accessories';
}
?>
    <!--YMM FORM -->

<?php if(count($list) > 0): ?>
    <div class="container">
        <h1> <?php echo $this->getAutoName() . $titlePrefix; ?></h1>
        <div class="listing-top-text">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing-top-' . $blockowner)->toHtml(); ?>
        </div>
        <?php if (!empty($subtitle)) : ?>
        <p style="text-align:left;"><?php echo $subtitle; ?></p>
        <?php endif; ?>
        <div id="weekly_featured_product">
            <div class="row product-list-container">
                <?php foreach ($list as $item): ?>
                    <div class="product-item-container col-sm-4 col-xs-12">
                                 <?php if($this instanceof Homebase_Autopart_Block_Category_Model):?>
                                 <div class="product-item-thumb">
                                    <?php $path = '#'; ?>
                                   <?php if($this instanceof Homebase_Autopart_Block_Category_Model):?>
                                        <div class="year-<?php echo $item->getLabel(); ?>">
                                            <div class="year-text"><?php echo $item->getLabel(); ?></div>
                                            <style type="text/css">
                                                .year-<?php echo $item->getLabel(); ?>{
                                                        display: none;
                                                }
                                            </style>
                                        </div>
                                    <?php else: ?>
                                        <?php $path =$this->getImage($item->getModel(), true, 198, 116); ?>
                                        <img src="<?php echo $path; ?>" class="check">
                                    <?php endif; ?>
                                </div>
                                     <a href="<?php echo $this->getCustomLink($item->getLabel()); ?>"><?php echo $item->getLabel(); ?> <?php echo $this->getAutoName(); ?> <i class="fa fa-angle-right" style="float: right;font-size: 24px;margin-top: -5px;"></i></a>
                                 <?php else: ?>
                                    <a href="<?php echo $this->getCustomLink($item->getLabel()); ?>">
                                    <div class="product-item-thumb">
                                    <?php $path = '#'; ?>
                                   <?php if($this instanceof Homebase_Autopart_Block_Category_Model):?>
                                        <div class="year-<?php echo $item->getLabel(); ?>">
                                            <div class="year-text"><?php echo $item->getLabel(); ?></div>
                                            <style type="text/css">
                                                .year-<?php echo $item->getLabel(); ?>{
                                                        display: none;
                                                }
                                            </style>
                                        </div>
                                    <?php else: ?>
                                        <?php $path =$this->getImage($item->getModel(), true, 198, 116); ?>
                                        <img src="<?php echo $path; ?>" class="check">
                                    <?php endif; ?>
                                </div>
                                    <?php echo $item->getName(); ?>
                                    </a>
                                 <?php endif; ?>

                        </div>
                <?php endforeach; ?>
            </div>
        </div>
<div class="full-wrapper">
      <div class="container">
          <div class="col-md-12">
              <?php echo $this->getChildHtml('category.partname') ?>
          </div>
      </div>
</div>
<div class="container">
    <div class="col-md-12">
        <?php echo $this->getChildHtml('category.popular.product') ?>
    </div>
</div>
<div id="shop-cat">
<?php echo $this->getLayout()->createBlock('hauto/home_shopby_category')->setTemplate('/hauto/home/shopby/category.phtml')->toHtml();
?>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
         jQuery('#shop-cat').detach().insertBefore('.footer-container ');         
    });
  
</script>

<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <script type="text/javascript">
        jQuery(document).ready(function(){

            jQuery('img').imageFallback(['<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>category/model-watermark.png']);

        });
    </script>

    
<?php else: ?>
    <div class="std">
        <h1 style="text-align:center;margin: 20px 0; font-size: 70px;margin-top:70px">No Product Found<i class="icon-doc"></i></h1>
        <p style="text-align:center; font-size: 15px;">Please select another category that have products.</a></p>
    </div>
<?php endif; ?>