<?php
$_helper = Mage::helper('cmsblog');
?>
<div class="cms-blog container">
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $this->getTitle() ?></h1>
            <?php if($_helper->isEnableDateDisplay()): ?>
                <div class="date">
                    <i class="fa fa-calendar" aria-hidden="true"></i>
                    <?php echo $this->getDateCreated() ?>
                </div>
            <?php endif; ?>
            <div class="content">
                <?php echo $this->getContent() ?>
            </div>
        </div>
    </div>
</div>