<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 6/28/17
 * Time: 7:51 PM
 */
$list = $this->getList();
?>
<div class="block block-layered-nav">
    <div class="block-title">
            <?php echo $this->__('Filter By ') ?>
    </div>

    <div class="block-content toggle-content">
        <div id="narrow-by-list">
            <div class="head col-sm-12 no-padding"><?php echo $this->getLayerTitle(); ?></div>
            <div class="content col-sm-12 no-padding">
                <ol style="display: none;">
                    <?php foreach($list as $item): ?>
                        <li data-val="<?php echo $item->getLabel(); ?>" class="">
                            <a href="<?php echo $item->getLink(); ?>">
                                <?php echo $item->getLabel(); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery('#narrow-by-list ol').show();
</script>