<?php
    $popularCollection = $this->popularProductCollection();
?>
<?php if(count($popularCollection) > 0 ): ?>
<div class="popular-products">
    <h2><?php echo  $this->__('Popular Products') ?></h2>
    <div class="row popular-wrapper">
        <?php foreach ($popularCollection as $product): ?>
        <div class="popular-item col-sm-4 col-xs-12">
            <div class="image">
                <a href="<?php echo $product['link'] ?>">
                    <img class="lazyload" data-src="<?php echo $product['image'] ?>" title="<?php echo $product['name'] ?>" alt="<?php echo $product['name'] ?>" />
                </a>
            </div>
            <div class="title">
                <a href="<?php echo $product['link'] ?>"><?php echo $product['name'] ?></a>
            </div>
            <div class="part_name">Part Number: <?php echo $product['part_number'] ?></div>
            <div class="price"><?php echo $product['price'] ?></div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>