<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 10/9/18
 * Time: 10:07 AM
 */

class Growthrocket_Content_Block_Content_Model extends Growthrocket_Content_Block_Content{
    const FITMENT_PARAM_MODEL = 'model';

    private $fitment = array();

    protected function _construct(){
        parent::_construct();
    }

    protected function _beforeToHtml()
    {
        $this->fitment = $this->getFitmentParams();
        $requestPath = substr($this->getRequest()->getRequestString(),1);
        $storeId = Mage::app()->getStore()->getId();
        $contentId = $this->sqlHelper->getPageContent($requestPath, self::FITMENT_PARAM_MODEL, $storeId);

        if($contentId){
            $this->setId($contentId);
        }else{
            $defaultContentId = Mage::getStoreConfig('grcontent/model/content');
            $this->setId($defaultContentId);
        }

        return $this; // TODO: Change the autogenerated stub
    }

    protected function getTemplateProcessor()
    {
        $processor = $this->helper->getModelTemplateProcessor();

        $processor->setFitment($this->fitment);
        return $processor;
    }
}