<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 6/26/17
 * Time: 6:01 PM
 */

$collection = $this->getListing();
$numberOfItem = ceil($collection->count()/ 4);
$begin = true;
$ctr = 1;
?>
<div id="shop-cat">
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <div class="shop-by-category">
                    <h2>
                        <?php if($this->getTitle()):?>
                            <?php echo $this->getTitle(); ?>
                        <?php else: ?>
                            Shop By Category
                        <?php endif;?>
                    </h2>
                    <div class="sby-category-listing">
                        <?php foreach($collection as $item): ?>
                            <?php if($begin): ?>
                                <div class="group-sby-group-listing  col-sm-3 col-xs-12">
                            <?php endif;  ?>
                            <?php if($item->getIid() != 438):?>
                                <a href="<?php echo $item->getLink(); ?>" class="link-item"><span><?php echo $item->getTitle(); ?></span></a>
                            <?php endif; ?>
                            <?php if($ctr % $numberOfItem == 0 || $ctr == $collection->count()): ?>
                                <?php $begin = true; ?>
                                </div>
                            <?php else: ?>
                                <?php $begin = false; ?>
                            <?php endif; ?>
                            <?php
                            $ctr++;
                            ?>
                        <?php endforeach; ?>
                        <div style="clear: both"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


