<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 19/11/2018
 * Time: 9:58 AM
 */
/** @var Mage_Core_Block_Template $this */

$path = pathinfo($this->getRequest()->getOriginalPathInfo(), PATHINFO_FILENAME);
$category = str_replace('-',' ', $path);
?>

<?php if(!Mage::registry('current_product')) : ?>
<div class="hero" style="background-image: url('<?php echo $this->getSkinUrl('images/category_banner.jpg'); ?>')">

</div>
<?php endif; ?>
