<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 19/11/2018
 * Time: 9:58 AM
 */
/** @var Mage_Core_Block_Template $this */

$path = pathinfo($this->getRequest()->getOriginalPathInfo(), PATHINFO_FILENAME);
$category = str_replace('-',' ', $path);
?>

<div class="hero" style="background-image: url('<?php echo $this->getSkinUrl('images/category_banner.jpg'); ?>')">
    <div class="fluid-container lfp-inner-md">
        <h1><?php echo uc_words($category,' '); ?></h1>
    </div>
</div>
