<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 1/22/18
 * Time: 9:21 PM
 */
$imgpath = Mage::getStoreConfig('design/header/logo_src');
$imgalt = Mage::getStoreConfig('design/header/logo_alt');
$b = Mage::getBaseUrl();
?>
<div id="footer-section">
    <?php echo $this->getChildHtml() ?>
    <div class="footer-container container-fluid">
        <div class="lfp-inner-md ">
            <div class="col-md-8 col-sm-9 col-xs-12 no-padding">
               <div class="row">
                   <div class="col-md-5 col-sm-5">

                           <div class="footer-trademark-container">
                               <div class="footer-logo">
                                   <span class="name"><?php echo Mage::getStoreConfig('general/store_information/name'); ?></span>
                               </div>
                               <div class="footer-trademark">
                                   <div class="col-sm-12 no-padding">
                                       <span class="address"> <?php echo Mage::getStoreConfig('general/store_information/address'); ?></span>
                                   </div>
                               </div>
                           </div>
                   </div>
                   <div class="col-md-6 col-sm-7">
                       <?php
                     echo  Mage::app()->getLayout()
                           ->createBlock('newsletter/subscribe')
                           ->setTemplate('newsletter/footer_subscribe.phtml')
                           ->toHtml();
                       ?>
                   </div>
               </div>
            </div>
            <div class="col-md-4 col-sm-3 col-xs-12  no-padding">
                <div class="footer-listing-1 footer-listing-2 col-md-6 col-sm-12 no-padding">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bottom_col4')->toHtml(); ?>
                </div>
                <div class="footer-listing-1 col-md-6 col-sm-12 no-padding">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bottom_col5')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="footer-copyright">
    <div class="container">
        <div class="col-md-12">
            <p><?php echo "Copyright © ".date('Y')." - Levittown Ford Parts - All rights reserved." ?></p>
        </div>
    </div>
</div>
<a href="#" id="totop"><i class="icon-up-open"></i></a>
<script type="text/javascript">
    var windowScroll_t;
    jQuery(window).scroll(function(){
        clearTimeout(windowScroll_t);
        windowScroll_t = setTimeout(function(){
            if(jQuery(this).scrollTop() > 100){
                jQuery('#totop').fadeIn();
            }else{
                jQuery('#totop').fadeOut();
            }
        }, 500);
    });
    jQuery('#totop').click(function(){
        jQuery('html, body').animate({scrollTop: 0}, 600);
        return false;
    });
    jQuery(function($){
        $(".cms-index-index .footer-container.fixed-position .footer-top,.cms-index-index .footer-container.fixed-position .footer-middle").remove();
    });
</script>
