<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?php echo Mage::getStoreConfig('gta/gta_groups/key'); ?>');</script>
<!-- End Google Tag Manager -->
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<?php $routeAction = $this->getRequest()->getActionName(); ?>
<?php if($routeAction === 'ymms') :?>
    <meta name="robots" content="NOINDEX,FOLLOW" />
<?php else: ?>
    <meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<?php endif; ?>
<meta name="google-site-verification" content="v6IWdLDKowF4k2q4kWDvhY_D5I2LdSjO4Iu-scIe2wA">
<?php
$theme = Mage::helper('porto');
$charSubset = '&subset=latin';
$d = $theme->getCfgSectionDesign();
$s = $theme->getCfgSectionSettings();
if(!isset($s['general']['disable_responsive']) || (isset($s['general']['disable_responsive']) && !$s['general']['disable_responsive'])){
    ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <?php
}
?>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php //Include Google fonts character subsets (such as extended latin, cyrillic)
if (isset($d['font']['primary_char_latin_ext']) && $d['font']['primary_char_latin_ext']==1 )
    $charSubset .= ',latin-ext';
if (isset($d['font']['custom_char_subset']) && $d['font']['custom_char_subset'])
    $charSubset .= ','.$d['font']['custom_char_subset'];
$font_sizes = "%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic";
?>
<?php if ($d['font']['custom'] && $d['font']['primary_font_family_group'] == 'google'): ?>
    <link rel="stylesheet" href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $d['font']['primary_font_family']).$font_sizes; echo $charSubset; ?>' type='text/css' />
<?php else: ?>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen"/>
<?php endif;?>
<link href='//fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'/>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<script type="text/javascript">
    //<![CDATA[
    if (typeof dailydealTimeCountersCategory == 'undefined') {
        var dailydealTimeCountersCategory = new Array();
        var i = 0;
    }
    //]]>
</script>
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script>var $j = jQuery.noConflict(true);</script>
<!--<?php echo "Porto Magento Theme: v".Mage::getConfig()->getModuleConfig("Smartwave_Porto")->version; ?>-->