<?php
/** @var Mage_Core_Block_Template $this */
$p = Mage::getBaseUrl();

?>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lfp_homepage_top_category')->toHtml(); ?>
<?php $featuredProducts = Mage::app()->getLayout()->createBlock('featuredproduct/List')->collection(); ?>

<div id="feat-model">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('feat-model')->toHtml(); 
                ?> 
            </div>
        </div>
    </div>
</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('must_have_for_your_car')->toHtml(); ?>
<?php echo Mage::app()->getLayout()->createBlock('gr_bestseller/collection')->setTemplate('bestseller/list.phtml')->toHtml(); ?>
<div id="featured-product">
    <div class="container-fluid">
        <div class=" featured-product-wrapper">
            <div class="lfp-inner-home">
                <div class="row">
                    <?php if(Mage::helper('mobiledetect')->isDesktop() || Mage::helper('mobiledetect')->isTablet()) : ?>
                        <div class="col-md-3">
                            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lfp_homepage_banner_4')->toHtml(); ?>
                        </div>
                    <?php endif; ?>
                    <div class="col-md-9 col-xs-12 col-sm-12">
                        <div class="">
                            <div class="col-md-12 no-padding">
                                <h2>Featured Products</h2>
                            </div>
                        </div>
                        <div class=" lfp-for-desktop">
                            <div class="col-md-12">
                                <?php $defaultClass = "current"; ?>
                                <ul class="featured-list control-products">
                                    <?php foreach ($featuredProducts as $key => $tabLabel): ?>
                                        <li class="<?php echo $defaultClass; ?>" data-tab="<?php echo "tab-{$key}" ?>">
                                            <span><?php echo ucwords($tabLabel['model_label']) ?></span>
                                        </li>
                                    <?php
                                    $defaultClass = "";
                                    endforeach;
                                    ?>
                                </ul>
                                <hr class="feat-border"/>
                            </div>
                        </div>
                        <div class="lfp-for-mobile mobile-featured-selector">
                            <select>
                                <?php foreach ($featuredProducts as $key => $tabLabel): ?>
                                    <option value="<?php echo "tab-{$key}" ?>"><?php echo ucwords($tabLabel['model_label']) ?></option>
                                <?php endforeach; ?>
                            </select>
                            <i class="fa fa-caret-down"></i>
                        </div>
                        <div class="parent-tab-content">
                            <?php $defaultClass = "current"; $position = 1; ?>
                            <?php foreach ($featuredProducts as $key => $tabData): ?>
                                <div class="<?php echo "tab-{$key} {$defaultClass}" ?> tab-content">
                                    <div class="row">
                                    <?php foreach ($tabData['data'] as $item): ?>
                                    <?php $item['ga_tracking']['position'] = $position++; ?>
                                        <div class="col-md-6 col-sm-6 col-xs-12 ga-impressions ga-productClick" data-layer-variable="<?php echo htmlentities(json_encode($item['ga_tracking'])) ?>">
                                            <div class="card-product">
                                                <div class="card-product-image">
                                                    <a href="<?php echo $item['url'] ?>">
                                                        <img src="<?php echo $item['image_url'] ?>" height="232">
                                                    </a>
                                                </div>
                                                <div class="card-product-title">
                                                    <h5><a href="<?php echo $item['url'] ?>"><?php echo $item['name'] ?></a></h5>
                                                </div>
                                            </div>
                                        </div>
                                    <?php
                                        $defaultClass = "";
                                        endforeach;
                                    ?>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12 col-md-12">
                                            <div class="card-product-action-box">
                                                <a href="<?php echo $tabData['model_url']; ?>">
                                                    <button class="button"><?php echo "VIEW ALL {$tabData['model_label']} PARTS" ?></button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div id="bottom-banner-section">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage_about_us_banner')->toHtml(); ?>
        </div>
    </div>
    <div class="home-text-content">
        <div class="lfp-inner-home">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lfp_homepage_banner_3')->toHtml(); ?>
        </div>
    </div>
</div>

