<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 1/22/18
 * Time: 9:21 PM
 */
?>

<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
$footer = Mage::getStoreConfig('porto_settings/footer',$code);
$footer_class = ($footer['fixed_position_footer_enabled'])?" fixed-position":"";
?>
<div class="footer-container <?php echo $footer_class; ?>">
    <div class="footer">
        <?php
        if( $footer['footer_top_enabled'] ){
            ?>
            <div class="footer-top">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <?php
                            $area = 'footer_top_block';
                            $type = $footer[$area];
                            if( $type== 'twitter' ){
                                echo $this->getChildHtml('tweets');
                            }
                            if( $type == 'custom' ){
                                echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer['footer_top_custom'])->toHtml();
                            }

                            ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php
        }
        if( $footer['footer_middle_enabled'] ){
            ?>
            <div class="footer-middle">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-4">
                            <div class="block">
                                <div class="block-title">
                                    <strong>
                                        <span>JeepsAreUs.com</span>
                                    </strong>
                                </div>
                                <div class="block-content">
                                    <p style="margin:0; font-size:12px">111 Bond St. Westbury, NY 11590</p>
                                    <br>
                                    <div class="footer-block-payment">
                                        <ul>
                                            <li>
                                                <img src="<?php echo $this->getSkinUrl('images/payments/home_23.png'); ?>" alt="">
                                            </li>
                                            <li>
                                                <img src="<?php echo $this->getSkinUrl('images/payments/home_25.png'); ?>" alt="">
                                            </li>
                                            <li>
                                                <img src="<?php echo $this->getSkinUrl('images/payments/home_27.png'); ?>" alt="">
                                            </li>
                                            <li>
                                                <img src="<?php echo $this->getSkinUrl('images/payments/home_29.png'); ?>" alt="">
                                            </li>
                                            <li>
                                                <img src="<?php echo $this->getSkinUrl('images/payments/home_31.png'); ?>" alt="">
                                            </li>
                                            <li>
                                                <img src="<?php echo $this->getSkinUrl('images/payments/home_33.png'); ?>" alt="">
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12 col-md-4">
                            <div class="footer-menu-links row clearfix">
                                <div class="col-sm-12 col-md-6">
                                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bottom_col4')->toHtml(); ?>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bottom_col5')->toHtml(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-4 footer-vertical-separator">
                            <div class="block">
                                <div class="block-title">
                                    <strong>
                                        <span>SIGN UP FOR OUR NEWSLETTER</span>
                                    </strong>
                                </div>
                                <div class="block-content">
                                    <?php echo $this->getChildHtml('footer.newsletter'); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php
        }
        ?>
        <?php
        if( $footer['footer_bottom_enabled'] ){
            ?>
            <div class="footer-bottom text-center">
                <div class="container">
                    <address><?php echo "Copyright © ".date('Y')." - JeepsAreUs - All rights reserved." ?></address>
                    <?php if(isset($footer['footer_bottom_store_switcher']) && $footer['footer_bottom_store_switcher']) echo $this->getChildHtml("store_switcher"); ?>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
</div>
<a href="#" id="totop"><i class="icon-up-open"></i></a>
<script type="text/javascript">
    var windowScroll_t;
    jQuery(window).scroll(function(){
        clearTimeout(windowScroll_t);
        windowScroll_t = setTimeout(function(){
            if(jQuery(this).scrollTop() > 100){
                jQuery('#totop').fadeIn();
            }else{
                jQuery('#totop').fadeOut();
            }
        }, 500);
    });
    jQuery('#totop').click(function(){
        jQuery('html, body').animate({scrollTop: 0}, 600);
        return false;
    });
    jQuery(function($){
        $(".cms-index-index .footer-container.fixed-position .footer-top,.cms-index-index .footer-container.fixed-position .footer-middle").remove();
    });
</script>
