<?php $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>
<?php $urlmedia = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>
<div id="top-cat">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <h2>Top Selling Categories</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 col-xs-12 ">
                <img class="responsimg" src="<?php echo $urlmedia; ?>home/jau/0920/jru_interior.jpg"  data-responsimg320="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_320x548_0005_interior.jpg"
                     data-responsimg480="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_870x548_0005_interior.jpg"
                     data-responsimg-desktop="<?php echo $urlmedia; ?>home/jau/0920/jru_interior.jpg"/>
                <div class="text-img bottom-left">
                    <h4><a href="<?php echo $url; ?>category/interior-accessories.html">Interior Accessories</a></h4>
                    <ul>
                        <li><a href="<?php echo $url; ?>part/amplifier.html">Amplifiers</a></li>
                        <li><a href="<?php echo $url; ?>part/backup-camera.html">Backup Camera</a></li>
                        <li><a href="<?php echo $url; ?>part/barrier-net.html">Barrier Nets</a></li>
                        <li><a href="<?php echo $url; ?>part/bluetooth-kit.html">Bluetooth Kits</a></li>
                    </ul>
                </div>
                <div class="space"></div>
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <img class="responsimg" src="<?php echo $urlmedia; ?>home/jau/0920/jru_exterior.jpg" data-responsimg320="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_320x548_0004_exterior.jpg"
                             data-responsimg480="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_870x548_0004_exterior.jpg"
                             data-responsimg-desktop="<?php echo $urlmedia; ?>home/jau/0920/jru_exterior.jpg"/>
                        <div class="text-img top-left">
                            <h4><a href="<?php echo $url; ?>category/exterior-accessories.html">Exterior Accessories</a></h4>
                            <ul>
                                <li><a href="<?php echo $url; ?>part/wheel-flare.html">Wheel Flare</a></li>
                                <li><a href="<?php echo $url; ?>part/wheel.html">Wheel</a></li>
                                <li><a href="<?php echo $url; ?>part/trim-kit.html">Trim Kit</a></li>
                                <li><a href="<?php echo $url; ?>part/bezel.html">Bezel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="space"></div>
                    <div class="col-sm-12 col-xs-12">
                        <img class="responsimg" src="<?php echo $urlmedia; ?>home/jau/0920/jru_audio.jpg"  data-responsimg320="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_320x548_0002_audio.jpg"
                             data-responsimg480="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_870x548_0002_audio.jpg"
                             data-responsimg-desktop="<?php echo $urlmedia; ?>home/jau/0920/jru_audio.jpg"/>
                        <div class="text-img top-left">
                            <h4><a href="<?php echo $url; ?>category/remote-start-electronics-and-audio-accessories.html">Audio & Electronics</a></h4>
                            <ul>
                                <li><a href="<?php echo $url; ?>part/auxiliary-switch-bank.html">Auxiliary Switch Bank</a></li>
                                <li><a href="<?php echo $url; ?>part/bluetooth-kit.html">Bluetooth Kit</a></li>
                                <li><a href="<?php echo $url; ?>part/wiring-harness.html">Wiring Harness</a></li>
                                <li><a href="<?php echo $url; ?>part/remote-start.html">Remote Start</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <img class="responsimg" src="<?php echo $urlmedia; ?>home/jau/0920/jru_performance.jpg"  data-responsimg320="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_320x548_0001_performance.jpg"
                             data-responsimg480="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_870x548_0001_performance.jpg"
                             data-responsimg-desktop="<?php echo $urlmedia; ?>home/jau/0920/jru_performance.jpg"/>
                        <div class="text-img top-left">
                            <h4><a href="<?php echo $url; ?>category/mopar-performance-parts.html">Mopar Performance Parts</a></h4>
                            <ul>
                                <li><a href="<?php echo $url; ?>part/axle.html">Axle</a></li>
                                <li><a href="<?php echo $url; ?>part/steer-kit.html">Steer Kit</a></li>
                                <li><a href="<?php echo $url; ?>part/sway-bar.html">Sway Bar</a></li>
                                <li><a href="<?php echo $url; ?>part/transmission.html">Transmission</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="space"></div>
                    <div class="col-sm-12 col-xs-12">
                        <img class="responsimg" src="<?php echo $urlmedia; ?>home/jau/0920/jru_cargo.jpg" data-responsimg320="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_320x548_0000_cargo.jpg"
                             data-responsimg480="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_870x548_0000_cargo.jpg"
                             data-responsimg-desktop="<?php echo $urlmedia; ?>home/jau/0920/jru_cargo.jpg"/>
                        <div class="text-img top-left">
                            <h4 style="width: 100%"><a href="<?php echo $url; ?>category/cargo-towing-and-racking-accessories.html">Cargo, Towing and Racking Accessories</a></h4>
                            <ul>
                                <li><a href="<?php echo $url; ?>part/roof-rack.html">Roof Rack</a></li>
                                <li><a href="<?php echo $url; ?>part/tow-hook.html">Tow Hook</a></li>
                                <li><a href="<?php echo $url; ?>part/storage-bag.html">Storage Bag</a></li>
                                <li><a href="<?php echo $url; ?>part/cargo-mat.html">Cargo Mat</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="space"></div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12 col-xs-12 ">
                <img class="responsimg" src="<?php echo $urlmedia; ?>home/jau/0920/jru_tuneup.jpg"  data-responsimg320="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_320x548_0003_tuneup.jpg"
                     data-responsimg480="<?php echo $urlmedia; ?>home/jau/0920/JRU_Banners_870x548_0003_tuneup.jpg"
                     data-responsimg-desktop="<?php echo $urlmedia; ?>home/jau/0920/jru_tuneup.jpg"/>
                <div class="text-img bottom-right">
                    <h4><a href="<?php echo $url; ?>category/tuneup-and-maintenance-parts.html">Tune-Up Parts</a></h4>
                    <ul>
                        <li><a href="<?php echo $url; ?>part/air-filter.html">Air Filters</a></li>
                        <li><a href="<?php echo $url; ?>part/brake-pad.html">Brake Pads</a></li>
                        <li><a href="<?php echo $url; ?>part/cabin-air-filter.html">Cabin Air Filters</a></li>
                        <li><a href="<?php echo $url; ?>part/cooling-fan.html">Cooling Fans</a></li>
                        <li><a href="<?php echo $url; ?>part/engine-air-filter.html">Engine Air Filters</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="feat-model">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('feat-model')->toHtml(); 
                ?> 
            </div>
        </div>
    </div>
</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('must_have_for_your_car')->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage_about_us_banner')->toHtml(); ?>

<div class="spp-banner-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-content')->toHtml(); ?>
            </div>
        </div>
    </div>
</div>

<?php echo Mage::app()->getLayout()->createBlock('gr_bestseller/collection')->setTemplate('bestseller/list.phtml')->toHtml(); ?>

<div id="featured-product">
    <div id="featured-product-container" class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <h2>Featured Products</h2>
            </div>
        </div>
        <div class="row featured-list-container">
            <div class="col-sm-3 col-xs-12">
                <ul class="control-products">
                    <li class="current" data-tab="tab1">
                        <div>
                            <span class="none">Compass</span>
                        </div>
                    </li>
                    <li data-tab="tab2">
                        <div>
                            <span class="none">Commander</span>
                        </div>
                    </li>
                    <li data-tab="tab3">
                        <div>
                            <span class="none">Cherokee</span>
                        </div>
                    </li>
                    <li data-tab="tab4">
                        <div>
                            <span class="none">Grand Cherokee</span>
                        </div>
                    </li>
                    <li data-tab="tab5">
                        <div>
                            <span class="none">Renegade</span>
                        </div>
                    </li>
                    <li data-tab="tab6">
                        <div>
                            <span class="none">Liberty</span>
                        </div>
                    </li>
                    <li data-tab="tab7">
                        <div>
                            <span class="none">Patriot</span>
                        </div>
                    </li>
                    <li data-tab="tab8">
                        <div>
                            <span class="none">Wrangler JK</span>
                        </div>
                    </li>
                    <li data-tab="tab9">
                        <div>
                            <span class="none">Wrangler JL</span>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-sm-9 col-xs-12">
                <div class="tab1 tab-content current">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0023_Compass_Cherokee_Renegade_Patriot_Bike_Rack.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Bike Rack</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>If you've been looking for an elegant, convenient way to mount your bicycle on your vehicle's roof, look no further.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/tc591pro.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0022_Compass_Cherokee_Renegade_Patriot_Emblem_75th_Anniversary_Bronze.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Emblem</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Add a unique bronze accent to your vehicle with a 1941 emblem originally on the 75th Anniversary Edition.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/68268158ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0021_Compass_GrandCherokee_Patriot_Engine_Air_Filter.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Engine Air Filter</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Excellent filtration and dependable protection for long engine life</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/4891694aa.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0020_Compass_Cold_Air_Intake.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Cold Air Intake</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>This intake isdesigned to allow cooler outside air to flow through a directional cone filter, directly into the intake manifold</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/77060012ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-compass.html"><button class="btn btn-feat-view">VIEW MORE COMPASS PARTS</button></a>
                        </div>
                    </div>
                </div>
                <div class="tab2 tab-content">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0019_Commander_Fog_Lamp_Kit.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Fog Lamp</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Be safe while driving in inclement weather with our fog lamps.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82209354.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0018_Commander_GrandCherokee_Liberty_License_Plate_Frame_Black.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>License Plate Frame</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Made with a Black polyester powder-coated finish.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82213250ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0017_Commander_Liberty_License_Plate_Frame_Black_Jeep_Logo.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>License Plate Frame with Jeep Logo</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Make your Liberty stand out with this beautiful license plate frame.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82213252ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0016_Commander_License_Plate_Frame_Polished.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Polished License Plate Frame</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Make your Liberty stand out with this beautiful license plate frame.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82213249ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-commander.html"><button class="btn btn-feat-view">VIEW MORE COMMANDER PARTS</button></a>
                        </div>
                    </div>
                </div>
                <div class="tab3 tab-content">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0015_Cherokee_Exhaust_System.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Exhaust System</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Pump up the volume of your Jeep Cherokee with this Cat Back Exhaust System.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/p5153453.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0014_Cherokee_Skid_Plate.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Skid Plate</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Protect your car's vital underbody components while off-roading</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82214108ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0023_Compass_Cherokee_Renegade_Patriot_Bike_Rack.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Bike Rack</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>If you've been looking for an elegant, convenient way to mount your bicycle on your vehicle's roof, look no further.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/tc591pro.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0022_Compass_Cherokee_Renegade_Patriot_Emblem_75th_Anniversary_Bronze.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Emblem</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Add a unique bronze accent to your vehicle with a 1941 emblem originally on the 75th Anniversary Edition.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/68268158ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-cherokee.html"><button class="btn btn-feat-view">VIEW MORE CHEROKEE PARTS</button></a>
                        </div>
                    </div>
                </div>
                <div class="tab4 tab-content">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0013_GrandCherokee_Fog_Lamp_Bezels_Chrome.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Fog Lamp</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Be safe while driving in inclement weather with our fog lamps.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82212341ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0021_Compass_GrandCherokee_Patriot_Engine_Air_Filter.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Engine Air Filter</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Excellent filtration and dependable protection for long engine life.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/4891694aa.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0018_Commander_GrandCherokee_Liberty_License_Plate_Frame_Black.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>License Plate Frame</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Made with a Black polyester powder-coated finish.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82213250ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0012_GrandCherokee_Hellcat_Ignition_Coil_Cover_Left.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Ignition Coil Cover</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Ignition coil cover for the left side of the engine, same as production.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/68186393ad.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-grand-cherokee.html"><button class="btn btn-feat-view">VIEW MORE GRAND CHEROKEE PARTS</button></a>
                        </div>
                    </div>
                </div>
                <div class="tab5 tab-content">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0011_Renegade_Exhaust_System.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Exhaust System</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Pump up the volume of your Jeep Renegade with this Mopar Stainless Steel Exhaust System.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82214600.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0023_Compass_Cherokee_Renegade_Patriot_Bike_Rack.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Bike Rack</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>If you've been looking for an elegant, convenient way to mount your bicycle on your vehicle's roof, look no further.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/tc591pro.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0022_Compass_Cherokee_Renegade_Patriot_Emblem_75th_Anniversary_Bronze.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Emblem</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Add a unique bronze accent to your vehicle with a 1941 emblem originally on the 75th Anniversary Edition.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/68268158ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0010_Renegade_Tire_Compressor.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Tire Compressor</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Be ready for a roadside emergency with this genuine OEM tire compressor.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/68082668aa-fs.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-renegade.html"><button class="btn btn-feat-view">VIEW MORE RENEGADE PARTS</button></a>
                        </div>
                    </div>
                </div>
                <div class="tab6 tab-content">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0009_Liberty_Cabin_Air_Filter.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Cabin Air Filter</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Keep particles like pollen, dust, and sooty exhaust gases out of your interior cabin by providing an excellent filtering system.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/68033193aa.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0018_Commander_GrandCherokee_Liberty_License_Plate_Frame_Black.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>License Plate Frame</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Made with a Black polyester powder-coated finish.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82213250ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0017_Commander_Liberty_License_Plate_Frame_Black_Jeep_Logo.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>License Plate Frame with Jeep Logo</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Make your Liberty stand out with this beautiful license plate frame.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82213252ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0008_Liberty_EVTS_Silver_Impact_Upgrade.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>EVTS SilverImpact Upgrade</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Adds 24/7 Monitored Smash & Grab Protection to your Silver Service Plan.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82214066.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-liberty.html"><button class="btn btn-feat-view">VIEW MORE LIBERTY PARTS</button></a>
                        </div>
                    </div>
                </div>
                <div class="tab7 tab-content">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0023_Compass_Cherokee_Renegade_Patriot_Bike_Rack.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Bike Rack</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>If you've been looking for an elegant, convenient way to mount your bicycle on your vehicle's roof, look no further.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/tc591pro.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0022_Compass_Cherokee_Renegade_Patriot_Emblem_75th_Anniversary_Bronze.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Emblem</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Add a unique bronze accent to your vehicle with a 1941 emblem originally on the 75th Anniversary Edition.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/68268158ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0007_Patriot_Wheels.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Wheels</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Be confident in your off-road adventures with these wheels.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/5105078ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0021_Compass_GrandCherokee_Patriot_Engine_Air_Filter.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Engine Air Filter</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Excellent filtration and dependable protection for long engine life</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/4891694aa.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-patriot.html"><button class="btn btn-feat-view">VIEW MORE PATRIOT PARTS</button></a>
                        </div>
                    </div>
                </div>
                <div class="tab8 tab-content">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0006_JK_JL_Cargo_Tote.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Cargo Tote</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Keep your cargo organized while you're on the go with a durable, premium cargo tote.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82208566.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0005_JK_Performance_Lift_Kit.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Lift Kit</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>These reputable lift kits work perfectly with all Wrangler vehicle systems.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/77070095ad-fs.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0004_JK_Cold_Air_Intake.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Cold Air Intake</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Provide noticeable horsepower and torque gains under varying atmospheric conditions.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/77070052.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0003_JK_Grille_Appliques_Black.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Grille Applique</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Add a rugged, distinct look to your Wrangler JK.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/130630rr.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-wrangler-jk.html"><button class="btn btn-feat-view">VIEW MORE WRANGLER JK PARTS</button></a>
                        </div>
                    </div>
                </div>
                <div class="tab9 tab-content">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0006_JK_JL_Cargo_Tote.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Cargo Tote</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Keep your cargo organized while you're on the go with a durable, premium cargo tote.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82208566.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0002_JL_Off-Road_Light_Kit.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Off-Road Light Kit</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Light up your off-road experience with these genuine OEM LED Off-Road Lights.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82215385ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table left">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0001_JL_Brakes.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Brake Kit</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Be ready to take on the toughest terrain with confidence with this brake kit.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/77072434.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 tab-table right">
                            <div class="tab-content-container">
                                <div class="feat feat-img-container">
                                    <img src="<?php echo $urlmedia; ?>home/jau/featured/_0000_JL_Bumpers.jpg" alt="">
                                </div>
                                <div class="feat feat-content-container">
                                    <div class="feat-header">
                                        <h3>Bumpers</h3>
                                    </div>
                                    <div class="feat-body">
                                        <p>Give your Wrangler JL a great look and superior protection.</p>
                                    </div>
                                    <div class="feat-actions">
                                        <a href="<?php echo $url; ?>sku/82215115ab.html">LEARN MORE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row tab-action-container">
                        <div class="col-md-12">
                            <a href="<?php echo $url; ?>model/jeep-wrangler-jl.html"><button class="btn btn-feat-view">VIEW MORE WRANGLER JL PARTS</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .tab-content.current{
            display: inherit;


        }
        @keyframes fadein {
            from {
                opacity:1;
            }
            50% {
                opacity: 0;
            }
            to {
                opacity:1;
            }
        }

    </style>
    <script type="text/javascript">

        var timerInit = setInterval(function(){
            if(typeof jQuery !== 'undefined'){
                (function($){
                    $(document).ready(function(){
                        $('#shop-cat').detach().insertBefore('.footer-container ');

                        $('ul.control-products li').click(function(){
                            var tab_id = $(this).attr('data-tab');

                            $('ul.control-products li').removeClass('current');
                            $('ul.control-products li').removeClass('clr-border');
                            $(this).prev().addClass('clr-border');
                            $('.tab-content').removeClass('current');

                            $(this).addClass('current');
                            $("."+tab_id).addClass('current');
                        });
                        $('.responsimg').responsImg({
                            allowDownsize: false,
                            elementQuery: false,
                            delay: 250,
                            breakpoints: {
                                mobile: 320,
                                desktop: 960
                            }
                        });

                    });
                })(jQuery);
                clearInterval(timerInit);
            }
//            console.log("Find jQuery");
        },200);

    </script>
