
<?php $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>
<?php $url2 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);; ?>
<div id="top-cat">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <h2>Top Selling Categories</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 col-xs-12 "> 
                <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/interior2.jpg"  data-responsimg320="<?php echo $url2; ?>home/amp/AMP_m_09.jpg"
                     data-responsimg480="<?php echo $url2; ?>home/amp/AMP_m_09.jpg"
                     data-responsimg-desktop="<?php echo $url2; ?>home/amp/interior2.jpg"/>
                <div class="text-img bottom-left">
                    <h4><a href="<?php echo $url; ?>category/interior-accessories.html">Interior Accessories</a></h4>
                    <ul>
                        <li><a href="<?php echo $url; ?>part/amplifier.html">Amplifiers</a></li>
                        <li><a href="<?php echo $url; ?>part/backup-camera.html">Backup Camera</a></li>
                        <li><a href="<?php echo $url; ?>part/barrier-net.html">Barrier Nets</a></li>
                        <li><a href="<?php echo $url; ?>part/bluetooth-kit.html">Bluetooth Kits</a></li>
                    </ul>
                </div>
                <div class="space"></div>
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/exterior2.jpg" data-responsimg320="<?php echo $url2; ?>home/amp/exterior2.jpg"
                             data-responsimg480="<?php echo $url2; ?>home/amp/exterior2.jpg"
                             data-responsimg-desktop="<?php echo $url2; ?>home/amp/exterior2.jpg"/>
                        <div class="text-img top-left">
                            <h4><a href="<?php echo $url; ?>category/exterior-accessories.html">Exterior Accessories</a></h4>
                            <ul>
                                <li><a href="<?php echo $url; ?>part/wheel.html">Wheel</a></li>
                                <li><a href="<?php echo $url; ?>part/tow-hook.html">Tow Hook</a></li>
                                <li><a href="<?php echo $url; ?>part/parking-sensor.html">Parking Sensor</a></li>
                                <li><a href="<?php echo $url; ?>part/grille.html">Grille</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="space"></div>
                    <div class="col-sm-12 col-xs-12">
                        <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/audio2.jpg"  data-responsimg320="<?php echo $url2; ?>home/amp/audio2.jpg"
                             data-responsimg480="<?php echo $url2; ?>home/amp/audio2.jpg"
                             data-responsimg-desktop="<?php echo $url2; ?>home/amp/audio2.jpg"/>
                        <div class="text-img top-left">
                            <h4><a href="<?php echo $url; ?>category/remote-start-electronics-and-audio-accessories.html">Audio & Electronics</a></h4>
                            <ul>
                                <li><a href="<?php echo $url; ?>part/dvd-player.html">DVD Player</a></li>
                                <li><a href="<?php echo $url; ?>part/remote-start.html">Remote Start</a></li>
                                <li><a href="<?php echo $url; ?>part/speaker.html">Speaker</a></li>
                                <li><a href="<?php echo $url; ?>part/touch-screen-radio.html">Touch Screen Radio</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/performance2.jpg"  data-responsimg320="<?php echo $url; ?><?php echo $url2; ?>home/amp/performance2.jpg"
                             data-responsimg480="<?php echo $url2; ?>home/amp/performance2.jpg"
                             data-responsimg-desktop="<?php echo $url2; ?>home/amp/performance2.jpg"/>
                        <div class="text-img top-right">
                            <h4><a href="<?php echo $url; ?>category/mopar-performance-parts.html">Mopar Performance Parts</a></h4>
                            <ul>
                                <li><a href="<?php echo $url; ?>part/strut-tower-brace.html">Strut Tower Brace</a></li>
                                <li><a href="<?php echo $url; ?>part/wiring-harness.html">Wiring Harness</a></li>
                                <li><a href="<?php echo $url; ?>part/lowering-springs.html">Lowering Springs</a></li>
                                <li><a href="<?php echo $url; ?>part/sway-bar.html">Sway Bar</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="space"></div>
                    <div class="col-sm-12 col-xs-12">
                        <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/sidesteps2.jpg" data-responsimg320="<?php echo $url2; ?>home/amp/sidesteps2.jpg"
                             data-responsimg480="<?php echo $url2; ?>home/amp/sidesteps2.jpg"
                             data-responsimg-desktop="<?php echo $url2; ?>home/amp/sidesteps2.jpg"/>
                        <div class="text-img top-right">
                            <h4><a href="<?php echo $url; ?>category/cargo-towing-and-racking-accessories.html">Cargo, Towing & Racking Accessories</a></h4>
                            <ul>
                                <li><a href="<?php echo $url; ?>part/fifth-wheel-hitch.html">Fifth Wheel Hitch</a></li>
                                <li><a href="<?php echo $url; ?>part/skid-plate.html">Skid Plate</a></li>
                                <li><a href="<?php echo $url; ?>part/tow-hitch.html">Tow Hitch</a></li>
                                <li><a href="<?php echo $url; ?>part/roof-rack.html">Roof Rack</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="space"></div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12 col-xs-12 ">
                <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/tuneup2.jpg"  data-responsimg320="<?php echo $url2; ?>home/amp/AMP_m_19.jpg"
                     data-responsimg480="<?php echo $url2; ?>home/amp/AMP_m_19.jpg"
                     data-responsimg-desktop="<?php echo $url2; ?>home/amp/tuneup2.jpg"/>
                <div class="text-img bottom-right">
                    <h4><a href="<?php echo $url; ?>category/tuneup-and-maintenance-parts.html">Tune-Up Parts</a></h4>
                    <ul>
                        <li><a href="<?php echo $url; ?>part/air-filter.html">Air Filters</a></li>
                        <li><a href="<?php echo $url; ?>part/brake-pad.html">Brake Pads</a></li>
                        <li><a href="<?php echo $url; ?>part/cabin-air-filter.html">Cabin Air Filters</a></li>
                        <li><a href="<?php echo $url; ?>part/cooling-fan.html">Cooling Fans</a></li>
                        <li><a href="<?php echo $url; ?>part/engine-air-filter.html">Engine Air Filters</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="feat-model">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('feat-model')->toHtml(); 
                ?> 
            </div>
        </div>
    </div>
</div>


<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('must_have_for_your_car')->toHtml(); ?>
<div id="spp-banner">
    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/discounted2.jpg" width="100%;"  data-responsimg320="<?php echo $url2; ?>home/amp/discounted2.jpg"
         data-responsimg480="<?php echo $url2; ?>home/amp/discounted2.jpg" data-responsimg-desktop="<?php echo $url2; ?>home/amp/discounted2.jpg"/>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <div class="spp-banner-text">
                    <h4>All parts discounted up to</h4>
                    <h2>30% OFF LISTED PRICE</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="spp-banner-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-content')->toHtml(); ?>
            </div>
        </div>
    </div>
</div>
<?php echo Mage::app()->getLayout()->createBlock('gr_bestseller/collection')->setTemplate('bestseller/list.phtml')->toHtml(); ?>
<div id="featured-product">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <h2>Featured Products</h2>
                <ul class="control-products">
                    <li class="current" data-tab="tab1"><span class="none">Chrysler</span></li>
                    <li data-tab="tab2"><span class="none">Dodge</span></li>
                    <li data-tab="tab3"><span class="none">Jeep</span></li>
                    <li data-tab="tab4"><span class="none">Ram</span></li>
                </ul>
            </div>
        </div>
        <div class="tab1 tab-content current">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Chrysler_Roadside-Safety-Kit.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Chrysler_Roadside-Safety-Kit.jpg"/>
                    <div class="text-img-p">
                        <h4>Roadside Safety Kit</h4>
                        <p>Kit includes jumper cables, flashlight, tools, and much more. Soft-sided Red bag with Chrysler Winged Badge.</p>
                        <a href="<?php echo $url; ?>sku/82211983.html">Learn More</a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Chrysler_Cargo-Net.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Chrysler_Cargo-Net.jpg"/>
                    <div class="text-img-p">
                        <h4>Cargo Net</h4>
                        <p>Attaches to existing mounting points. Convenient and easy to setup.</p>
                        <a href="<?php echo $url; ?>sku/82210267.html">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="space"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Chrysler_Front-End-Covers.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Chrysler_Front-End-Covers.jpg"/>
                    <div class="text-img-p">
                        <h4>Front End Covers</h4>
                        <p>Accommodates vehicles with or without a front license plate. Chrysler Wing Logo. Black.</p>
                        <a href="<?php echo $url; ?>sku/82212692.html">Learn More</a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Chrysler_Air-Deflector.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Chrysler_Air-Deflector.jpg"/>
                    <div class="text-img-p">
                        <h4>Air Deflector</h4>
                        <p>This Hood Air Deflector features a wraparound style that creates an air stream to keep insects and road spray away.</p>
                        <a href="<?php echo $url; ?>cat/2017-chrysler-pacifica-exterior-accessories.html">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 margin-button">
                    <a class="button button-blue" href="<?php echo $url; ?>make/chrysler.html">VIEW MORE CHRYSLER PARTS</a>
                </div>
            </div>
        </div>

        <!-- -->
        <div class="tab2 tab-content">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Dodge_Cargo-Tote.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Dodge_Cargo-Tote.jpg"/>
                    <div class="text-img-p">
                        <h4>Cargo Tote</h4>
                        <p>Keep your trunk neat and organized, look no further than this convenient cargo tote!</p>
                        <a href="<?php echo $url; ?>sku/82208567ab.html">Learn More</a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Dodge_Bike-Rack.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Dodge_Bike-Rack.jpg"/>
                    <div class="text-img-p">
                        <h4>Bike Rack</h4>
                        <p>Bring your bike along with you on all of your adventures with this low-profile, fork-mount bike carrier by Thule. </p>
                        <a href="<?php echo $url; ?>sku/tcfkm526.html">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="space"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Dodge_Engine-Air-Filter.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Dodge_Engine-Air-Filter.jpg"/>
                    <div class="text-img-p">
                        <h4>Engine Air Filter</h4>
                        <p>Provides enhanced protection to help improve performance and fuel efficiency</p>
                        <a href="<?php echo $url; ?>sku/4891926aa.html">Learn More</a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Dodge_Tire-Compressor.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Dodge_Tire-Compressor.jpg"/>
                    <div class="text-img-p">
                        <h4>Tire Compressor</h4>
                        <p>Be ready for any roadside emergency with this genuine tire compressor.</p>
                        <a href="<?php echo $url; ?>sku/68082668aa-fs.html">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 margin-button">
                    <a class="button button-blue" href="<?php echo $url; ?>make/dodge.html">VIEW MORE DODGE Parts</a>
                </div>
            </div>
        </div>

        <div class="tab3 tab-content">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Jeep_Tail-Lamp-Bezels.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Jeep_Tail-Lamp-Bezels.jpg"/>
                    <div class="text-img-p">
                        <h4>Tail Lamp Bezels</h4>
                        <p>Swap out your Tail Lamp Bezels for these upgraded ones straight off of the Altitude Edition.</p>
                        <a href="<?php echo $url; ?>sku/sggctailbezelkit.html">Learn More</a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Jeep_Road-Safety-Kit.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Jeep_Road-Safety-Kit.jpg"/>
                    <div class="text-img-p">
                        <h4>Road Safety Kit</h4>
                        <p>This kit includes jumper cables, flashlight (with batteries) screwdrivers, pliers,
                            electrical tape, safety triangle, blanket, and gloves.</p>
                        <a href="<?php echo $url; ?>sku/82213499.html">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="space"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Jeep_Tire-Compressor.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Jeep_Tire-Compressor.jpg"/>
                    <div class="text-img-p">
                        <h4>Tire Compressor</h4>
                        <p>Be ready for any roadside emergency with this genuine tire compressor.</p>
                        <a href="<?php echo $url; ?>sku/68082668aa-fs.html">Learn More</a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Jeep_Oil-Filter.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Jeep_Oil-Filter.jpg"/>
                    <div class="text-img-p">
                        <h4>Oil Filter</h4>
                        <p>Minimize the risk of extended oil drains without compromising vehicle performance.</p>
                        <a href="<?php echo $url; ?>sku/4892339aa.html">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 margin-button">
                    <a class="button button-blue" href="<?php echo $url; ?>make/jeep.html">VIEW MORE JEEP PARTS</a>
                </div>
            </div>
        </div>

        <div class="tab4 tab-content">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Ram_Tow-Hitch.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Ram_Tow-Hitch.jpg"/>
                    <div class="text-img-p">
                        <h4>Tow Hitch Receiver</h4>
                        <p>Surpasses extensive road testing for strength and durability</p>
                        <a href="<?php echo $url; ?>sku/82214340ab.html">Learn More</a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Ram_Wheels.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Ram_Wheels.jpg"/>
                    <div class="text-img-p">
                        <h4>Wheels</h4>
                        <p>Exclusively from the Black RAM Edition</p>
                        <a href="<?php echo $url; ?>sku/1ub17dx8ac.html">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="space"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Ram_Floor-Mats.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Ram_Floor-Mats.jpg"/>
                    <div class="text-img-p">
                        <h4>Floor Mats</h4>
                        <p>Premium carpets for your Ram.</p>
                        <a href="<?php echo $url; ?>sku/82213395ab.html">Learn More</a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/amp/AMP_Ram_Backup-Cam.jpg"  data-responsimg-desktop="<?php echo $url2; ?>home/amp/AMP_Ram_Backup-Cam.jpg"/>
                    <div class="text-img-p">
                        <h4>Backup Camera System</h4>
                        <p>Includes wide-angle weather-proof camera wiring harness from camera to radio installation</p>
                        <a href="<?php echo $url; ?>sku/82214240ab.html">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 margin-button">
                    <a class="button button-blue" href="<?php echo $url; ?>make/ram.html">VIEW MORE RAM PARTS</a>
                </div>
            </div>
        </div>

    </div>
    <style>
        ul.control-products li.current{
            color: black;
        }

        .tab-content{
            display: none;
            animation: fadein 1s;

        }

        .tab-content.current{
            display: inherit;


        }
        @keyframes fadein {
            from {
                opacity:1;
            }
            50% {
                opacity: 0;
            }
            to {
                opacity:1;
            }
        }

    </style>
    <script type="text/javascript">

        var timerInit = setInterval(function(){
            if(typeof jQuery !== 'undefined'){
                (function($){
                    $(document).ready(function(){
                        $('#shop-cat').detach().insertBefore('.footer-container ');

                        $('ul.control-products li').click(function(){
                            var tab_id = $(this).attr('data-tab');

                            $('ul.control-products li').removeClass('current');
                            $('.tab-content').removeClass('current');

                            $(this).addClass('current');
                            $("."+tab_id).addClass('current');
                        });

                    });
                })(jQuery);
                clearInterval(timerInit);
            }
//            console.log("Find jQuery");
        },200);

    </script>
