<?php
$partCollection = $this->partCollection();
if(!empty($partCollection)): ?>
    <div class="row">
        <div class="col-sm-12 part-heading">
            <h2><?php echo $this->getMakeModelName() . $this->__(' Parts & Accessories') ?></h2>
        </div>
    </div>
    <div class="row part-model-list">
    <?php foreach ($partCollection as $item): ?>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="part-list-container">
                <a href="<?php echo $item['link'] ?>">
                   <span> <?php echo $item['name'] ?></span>
                    <i class="fine-angle"></i>
                </a>
            </div>
        </div >
    <?php endforeach; ?>
    </div>
<?php endif ?>
