<?php
/**
 * Created by PhpStorm.
 * User: olivercastro
 * Date: 12/03/2017
 * Time: 9:41 AM
 */

class Homebase_Autopart_Block_Partcategory extends Mage_Core_Block_Template{
    /** @var  Homebase_Autopart_Helper_Data $_helper */
    protected $_helper;
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setTemplate('homebase/menu/partcategory.phtml');
        $this->_helper = Mage::helper('hautopart');
    }

    public function getMakes(){
        /** @var Homebase_Autopart_Model_Resource_Combination_Collection $_makes */
        $_makes = Mage::getModel('hautopart/combination')->getCollection();
        $_makes->getSelect()->group('make');
        $makes = $_makes->getColumnValues('make');
        $makelabel = array();
        foreach($makes as $make){
            $makelabel[] = array(
                'id' => $make,
                'label' => $this->_helper->getOptionValue($make)
            );
        }
        return $makelabel;
    }

    public function getModels($makeId){
        /** @var Homebase_Autopart_Model_Resource_Combination_Collection $_makes */
        $_makes = Mage::getModel('hautopart/combination')->getCollection();
        $_makes->addFieldToFilter('make',$makeId)
            ->getSelect()->group('model');
        $models = $_makes->getColumnValues('model');
        $modelLabels = array();
        foreach($models as $model){
            $modelLabels[] = array(
                'id'    => $model,
                'label' => $this->_helper->getOptionValue($model)
            );
        }
        return $modelLabels;
    }

}