<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 2/28/17
 * Time: 10:40 PM
 */

class Homebase_Autopart_Block_Adminhtml_Combination_Grid extends Mage_Adminhtml_Block_Widget_Grid{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setDefaultSort('id');
        $this->setId('hautopart_combination_grid');
        $this->setDefaultDir('asc');
        $this->setSaveParametersInSession(true);
    }
    protected function _getCollectionClass(){
        return 'hautopart/combination_collection';
    }
    protected function _prepareCollection()
    {
        /** @var Homebase_Autopart_Model_Resource_Combination_Collection $collection */
        $collection = Mage::getResourceModel($this->_getCollectionClass());

        $collection->getSelect()->join(array('y' => 'auto_combination_list_labels'),' year=y.option',
            array('ylabel' => 'label'));

        $collection->getSelect()->join(array('m' => 'auto_combination_list_labels'),' make=m.option',
            array('mlabel' => 'label'));

        $collection->getSelect()->join(array('mm' => 'auto_combination_list_labels'),' model=mm.option',
            array('mmlabel' => 'label'));

        $this->setCollection($collection);
        return parent::_prepareCollection();
    }

    protected function _prepareColumns()
    {
        $this->addColumn('id',
            array(
                'header'=> $this->__('ID'),
                'align' =>'right',
                'width' => '10px',
                'index' => 'id'
            )
        );

        $this->addColumn('year',
            array(
                'header'=> $this->__('Year Value'),
                'align' =>'center',
                'index' => 'ylabel',
                'filter_index' => 'y.label'
            )
        );
        $this->addColumn('make',
            array(
                'header'=> $this->__('Make Value'),
                'align' =>'left',
                'index' => 'mlabel',
                'filter_index' => 'm.label'
            )
        );
        $this->addColumn('model',
            array(
                'header'=> $this->__('Model Value'),
                'align' =>'right',
                'index' => 'mmlabel',
                'filter_index' => 'mm.label'
            )
        );
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }
    public function getRowUrl($item)
    {
        return $this->getUrl('*/*/edit',array('id'  =>  $item->getId()));
    }
}