<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 1/22/18
 * Time: 9:21 PM
 */
$imgpath = Mage::getStoreConfig('design/header/logo_src');
$imgalt = Mage::getStoreConfig('design/header/logo_alt');
$b = Mage::getBaseUrl();
?>
<?php echo $this->getChildHtml('footer_shopby'); ?>
<div id="footer-section">
    <div class="footer-container container-fluid<?php echo $footer_class; ?>">
        <div class="container">
            <div class="col-md-4 col-sm-12">
                <div class="footer-trademark-container">
                    <div class="footer-logo">
                        <img src="<?php echo $this->getSkinUrl($imgpath); ?>" alt="<?php echo $imgalt;?>"/>
                    </div>
                    <div class="footer-trademark">
                        <p>RAMSAREUS.com</p>
                        <p>283 N.Franklin St.Hempstead, NY 11550</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bottom_col4')->toHtml(); ?>  
            </div>
            <div class="col-md-4 col-sm-6">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bottom_col5')->toHtml(); ?>
        </div>
    </div>
</div>
<div class="footer-newsletter">
    <div class="container-fluid">
        <div class="container">
            <?php echo $this->getChildHtml('footer.newsletter'); ?>
        </div>
        </div>
    </div>
    <div class="container footer-copyright">
        <div class="col-md-6">
            <p><?php echo "&copy; Copyright " . date('Y') ." RAMSAREUS.com. All rights reserved." ?></p>
        </div>
        <div class="col-md-6" style="text-align:right">
            <img src="<?php echo $this->getSkinUrl('images/payment/methods.png'); ?>"/>
        </div>
    </div>
</div>
<a href="#" id="totop"><i class="icon-up-open"></i></a>
<script type="text/javascript">
    var windowScroll_t;
    jQuery(window).scroll(function(){
        clearTimeout(windowScroll_t);
        windowScroll_t = setTimeout(function(){
            if(jQuery(this).scrollTop() > 100){
                jQuery('#totop').fadeIn();
            }else{
                jQuery('#totop').fadeOut();
            }
        }, 500);
    });
    jQuery('#totop').click(function(){
        jQuery('html, body').animate({scrollTop: 0}, 600);
        return false;
    });
    jQuery(function($){
        $(".cms-index-index .footer-container.fixed-position .footer-top,.cms-index-index .footer-container.fixed-position .footer-middle").remove();
    });
</script>
