<?php
/** @var Mage_Core_Block_Template $this */
$p = Mage::getBaseUrl();

?>
<?php $url2 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);; ?>
<div id="top-cat">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <h2>Top Selling Categories</h2>
            </div>
        </div>
        <div class="row category-card-row">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="category-card">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/rau/interior_accessories.png"  data-responsimg320="<?php echo $url2; ?>home/rau/interior_accessories.png"
                         data-responsimg480="<?php echo $url2; ?>home/rau/interior_accessories.png"
                         data-responsimg-desktop="<?php echo $url2; ?>home/rau/interior_accessories.png"/>
                    <div class="card-top">
                        <h4><a href="<?php echo $p; ?>category/interior-accessories.html">Interior Accessories</a></h4>
                        <ul>
                            <li><a href="<?php echo $p ?>part/backup-camera.html">Backup Camera</a></li>
                            <li><a href="<?php echo $p ?>part/first-aid-kit.html">First Aid Kit</a></li>
                            <li><a href="<?php echo $p ?>part/pedal-cover.html">Pedal Cover</a></li>
                            <li><a href="<?php echo $p ?>part/storage-tote.html">Storage Tote</a></li>
                        </ul>
                    </div>
                    <div class="card-bottom">
                        <a href="<?php echo $p; ?>category/interior-accessories.html">
                            <button class="btn btn-maroon">
                            <span>
                                <span>Browse Parts</span>
                            </span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="category-card">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/rau/media_accessories.png"  data-responsimg320="<?php echo $url2; ?>home/rau/media_accessories.png"
                         data-responsimg480="<?php echo $url2; ?>home/rau/media_accessories.png"
                         data-responsimg-desktop="<?php echo $url2; ?>home/rau/media_accessories.png"/>

                    <div class="card-top">
                        <h4><a href="<?php echo $p; ?>category/remote-start-electronics-and-audio-accessories.html">Audio & Media Accessories</a></h4>
                        <ul>
                            <li><a href="<?php echo $p ?>part/bed-light.html">Bed Light</a></li>
                            <li><a href="<?php echo $p ?>part/headphone.html">Headphone</a></li>
                            <li><a href="<?php echo $p ?>part/remote-start.html">Remote Start</a></li>
                            <li><a href="<?php echo $p ?>part/wire-harness.html">Wire Harness</a></li>
                        </ul>
                    </div>
                    <div class="card-bottom">
                        <a href="<?php echo $p; ?>category/remote-start-electronics-and-audio-accessories.html">
                            <button class="btn btn-maroon">
                            <span>
                                <span>Browse Parts</span>
                            </span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="category-card">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/rau/performance_parts.png"  data-responsimg320="<?php echo $url2; ?>home/rau/performance_parts.png"
                         data-responsimg480="<?php echo $url2; ?>home/rau/performance_parts.png"
                         data-responsimg-desktop="<?php echo $url2; ?>home/rau/performance_parts.png"/>

                    <div class="card-top">
                        <h4><a href="<?php echo $p; ?>category/mopar-performance-parts.html">Performance Parts</a></h4>
                        <ul>
                            <li><a href="<?php echo $p ?>part/aandc-expansion-kit.html">A/C Expansion Kit</a></li>
                            <li><a href="<?php echo $p ?>part/crate-engine-wiring-kit.html">Crate Engine Wiring Kit</a></li>
                            <li><a href="<?php echo $p ?>part/hood.html">Hood</a></li>
                            <li><a href="<?php echo $p ?>part/transmission.html">Transmission</a></li>
                        </ul>
                    </div>
                    <div class="card-bottom">
                        <a href="<?php echo $p; ?>category/mopar-performance-parts.html">
                            <button class="btn btn-maroon">
                            <span>
                                <span>Browse Parts</span>
                            </span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row category-card-row">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="category-card">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/rau/exterior_accessories.png"  data-responsimg320="<?php echo $url2; ?>home/rau/exterior_accessories.png"
                         data-responsimg480="<?php echo $url2; ?>home/rau/exterior_accessories.png"
                         data-responsimg-desktop="<?php echo $url2; ?>home/rau/exterior_accessories.png"/>
                    <div class="card-top">
                        <h4><a href="<?php echo $p; ?>category/exterior-accessories.html">Exterior Accessories</a></h4>
                        <ul>
                            <li><a href="<?php echo $p ?>part/decal.html">Decal</a></li>
                            <li><a href="<?php echo $p ?>part/headlamp.html">Headlamp</a></li>
                            <li><a href="<?php echo $p ?>part/tail-light.html">Tail Light</a></li>
                            <li><a href="<?php echo $p ?>part/window-molding.html">Window Molding</a></li>
                        </ul>
                    </div>
                    <div class="card-bottom">
                        <a href="<?php echo $p; ?>category/exterior-accessories.html">
                            <button class="btn btn-maroon">
                            <span>
                                <span>Browse Parts</span>
                            </span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="category-card">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/rau/towing_accessories.png"  data-responsimg320="<?php echo $url2; ?>home/rau/towing_accessories.png"
                         data-responsimg480="<?php echo $url2; ?>home/rau/towing_accessories.png"
                         data-responsimg-desktop="<?php echo $url2; ?>home/rau/towing_accessories.png"/>
                    <div class="card-top">
                        <h4><a href="<?php echo $p;?>category/cargo-towing-and-racking-accessories.html">Towing Accessories</a></h4>
                        <ul>
                            <li><a href="<?php echo $p ?>part/cargo-carrier.html">Cargo Carrier</a></li>
                            <li><a href="<?php echo $p ?>part/roof-side-rails.html">Roof Side Rails</a></li>
                            <li><a href="<?php echo $p ?>part/tow-hitch-plug.html">Tow Hitch Plug</a></li>
                            <li><a href="<?php echo $p ?>part/wiring-harness-repair-kit.html">Wiring Harness Repair Kit</a></li>
                        </ul>
                    </div>
                    <div class="card-bottom">
                        <a href="<?php echo $p;?>category/cargo-towing-and-racking-accessories.html">
                            <button class="btn btn-maroon">
                            <span>
                                <span>Browse Parts</span>
                            </span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="category-card">
                    <img class="responsimg lazyload" data-src="<?php echo $url2; ?>home/rau/maintenance_parts.png"  data-responsimg320="<?php echo $url2; ?>home/rau/maintenance_parts.png"
                         data-responsimg480="<?php echo $url2; ?>home/rau/maintenance_parts.png"
                         data-responsimg-desktop="<?php echo $url2; ?>home/rau/maintenance_parts.png"/>
                    <div class="card-top">
                        <h4><a href="<?php echo $p; ?>category/tuneup-and-maintenance-parts.html">Maintenance Parts</a></h4>
                        <ul>
                            <li><a href="<?php echo $p ?>part/air-filter.html">Air Filter</a></li>
                            <li><a href="<?php echo $p ?>part/oil-filter.html">Oil Filter</a></li>
                            <li><a href="<?php echo $p ?>part/wiper-blade.html">Wiper Blade</a></li>
                            <li><a href="<?php echo $p ?>part/engine-air-filter.html">Engine Air Filter</a></li>
                        </ul>
                    </div>
                    <div class="card-bottom">
                        <a href="<?php echo $p; ?>category/tuneup-and-maintenance-parts.html">
                            <button class="btn btn-maroon">
                            <span>
                                <span>Browse Parts</span>
                            </span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="feat-model">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('feat-model')->toHtml(); 
                ?> 
            </div>
        </div>
    </div>
</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('must_have_for_your_car')->toHtml(); ?>
<?php echo Mage::app()->getLayout()->createBlock('gr_bestseller/collection')->setTemplate('bestseller/list.phtml')->toHtml(); ?>

<div id="featured-product">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="card-sidebar">
                    <img class="lazyload" data-src="<?php echo $url2; ?>home/rau/sidebar_banner.png" alt=""/>
                    <div class="card-sidebar-header">
                        <p class="p-regular">We are an</p>
                        <p class="p-strong">AUTHORIZED<br/>FACTORY<br/>RETAILER</p>
                        <p class="p-regular">of</p>
                        <p class="p-strong">RAM<br/>PARTS</p>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12 no-padding">
                        <h2>Featured Products</h2>
                    </div>
                </div>
                <div class="row hidden-xs">
                    <div class="col-md-12">
                        <ul class="featured-list control-products">
                            <li class="current" data-tab="tab1">
                                <span>1500 DS</span>
                            </li>
                            <li data-tab="tab2">
                                <span>2500</span>
                            </li>
                            <li data-tab="tab3">
                                <span>3500</span>
                            </li>
                            <li data-tab="tab4">
                                <span>4500</span>
                            </li>
                            <li data-tab="tab5">
                                <span>PROMASTER</span>
                            </li>
                            <li data-tab="tab6">
                                <span>PROMASTER CITY</span>
                            </li>
                        </ul>
                        <hr class="feat-border"/>
                    </div>
                </div>
                <div class="row hidden-xs">
                    <div class="col-md-12">
                        <div class="tab1 tab-content current">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/t/c/tcfkm526-18-1.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Bike Rack</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Bring your bike along with you on all of your adventures with this low-profile, fork-mount bike carrier by Thule. </p>
                                            <br/>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/tcfkm526ab.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215407-amp.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Carpet Mats</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Genuine OEM floor mats from Ram are made to hug the contours of your truck's footwells for excellent protection against daily wear and tear</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p;?>sku/82215407.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215475.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Air Deflectors</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Equip your truck with a rugged hood deflector to keep road debris, dirt, and bugs from hitting your hood and windshield.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82215475.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                    <div class="card-product-action-box">
                                        <a href="<?php echo $p; ?>model/ram-1500.html">
                                            <button class="button">VIEW ALL RAM 1500 DS PARTS</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab2 tab-content">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215109.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Warn Winch</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Equip your truck with a genuine OEM Warn Winch from Ram Performance to increase your truck's hauling capacity.</p>
                                            <br/>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82215109.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                               <?php /* <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img src="<?php echo $url2; ?>catalog/product/8/2/82212951.png" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Genuine Ram Cooler</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>This cooler is designed with outdoor use in mind, suitable for all your adventures.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p;?>sku/82212951.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div> */ ?>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/r/a/ram_2500_82211653.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Storage Bins</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>This genuine OEM Storage Lock will keep your valuables safe and secure in your cab, even when you're not in your truck.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82211653.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                    <div class="card-product-action-box">
                                        <a href="<?php echo $p; ?>model/ram-2500.html">
                                            <button class="button">VIEW ALL RAM 2500 PARTS</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab3 tab-content">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82214148.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Bed Extenders</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>This popular Bed Extender connects to the rear of the bed and pivots in and out for extra storage and efficiency.</p>
                                            <br/>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82214148.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/m/o/moparcabinairfilter-jpg_1_1.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Cabin Air Filters</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>This cabin air filter keeps particles like pollen, dust, and sooty exhaust gases out of your vehicle's cabin.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p;?>sku/68406048aa.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215553-a.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Remote Start Kits</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Warm up your truck on a cold winter day, or cool it down on a hot summer day with just the push of a button. A genuine OEM remote start kit from Ram is made to work seamlessly with your vehicle's electronic security key.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82215553.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                    <div class="card-product-action-box">
                                        <a href="<?php echo $p; ?>model/ram-3500.html">
                                            <button class="button">VIEW ALL RAM 3500 PARTS</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab4 tab-content">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215194-a.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Hitches</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Cut your trailer connection time while reducing injuries caused by lifting trailers.</p>
                                            <br/>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82215194.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82213395ab.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Floor Mats</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Genuine OEM floor mats from Ram are made to hug the contours of your truck's footwells for excellent protection against daily wear and tear</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p;?>sku/82213395ab.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82212765-sm.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Air Deflectors</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>This genuine OEM Ram Air Deflector features a wraparound style that helps create an air stream to direct insects and road debris up and away from your truck's hood and windshield.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82212765.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                    <div class="card-product-action-box">
                                        <a href="<?php echo $p; ?>model/ram-4500.html">
                                            <button class="button">VIEW ALL RAM 4500 PARTS</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab5 tab-content">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82213499-1_1_.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Roadside Safety Kits</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Be ready for nearly any roadside emergency with this Roadside Safety Kit from Ram.</p>
                                            <br/>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82213499.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/m/o/moparcabinairfilter-jpg_1_2.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Cabin Air Filters</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>This cabin air filter keeps particles like pollen, dust, and sooty exhaust gases out of your vehicle's cabin.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p;?>sku/68169308aa.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82214048.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Fog Lamp Kits</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>If you're going to be out on the road in extreme weather, keep yourself safe with these Ram OEM fog lights.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/82214048.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                    <div class="card-product-action-box">
                                        <a href="<?php echo $p; ?>model/ram-promaster.html">
                                            <button class="button">VIEW ALL RAM PROMASTER PARTS</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab6 tab-content">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/t/c/tcfkm526-18-1.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Bike Rack</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Bring your bike along with you on all of your adventures with this low-profile, fork-mount bike carrier by Thule. </p>
                                            <br/>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/tcfkm526ab.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82209422ab-17.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Cargo Nets</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>Keep everything in place until you get where you're going. The flexible black cargo net is kept in place using 14 plastic hooks.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p;?>sku/82209422ab.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <div class="card-product">
                                        <div class="card-product-image">
                                            <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/t/r/trab4553-6.jpg" alt="">
                                        </div>
                                        <div class="card-product-title">
                                            <h5>Roof Racks</h5>
                                        </div>
                                        <div class="card-product-content">
                                            <p>This removable roof rack by Thule enhances your vehicle with sturdy brushed aluminum, multipurpose cross rails.</p>
                                            <div class="card-product-action">
                                                <a href="<?php echo $p; ?>sku/trab4553.html">LEARN MORE</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                    <div class="card-product-action-box">
                                        <a href="<?php echo $p; ?>model/ram-promaster-city.html">
                                            <button class="button">VIEW ALL RAM PROMASTER CITY PARTS</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row visible-xs">
                    <div class="col-xs-12 no-padding">
                        <div class="custom-select">
                            <select name="" id="">
                                <option value="0">1500 DS</option>
                                <option value="1">1500 DS</option>
                                <option value="2">2500</option>
                                <option value="3">3500</option>
                                <option value="4">4500</option>
                                <option value="5">Promaster</option>
                                <option value="6">Promaster City</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-12 no-padding">
                        <div class="slides-container">
                            <div id="slide-1" class="slid">
                                <div class="slide">
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/t/c/tcfkm526-18-1.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Bike Rack</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Bring your bike along with you on all of your adventures with this low-profile, fork-mount bike carrier by Thule. </p>
                                                <br/>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/tcfkm526ab.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215407-amp.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Carpet Mats</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Genuine OEM floor mats from Ram are made to hug the contours of your truck's footwells for excellent protection against daily wear and tear</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p;?>sku/82215407.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215475.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Air Deflectors</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Equip your truck with a rugged hood deflector to keep road debris, dirt, and bugs from hitting your hood and windshield.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82215475.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="slide-2" class="slid" style="display: none;">
                                <div class="slide">
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215109.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Warn Winch</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Equip your truck with a genuine OEM Warn Winch from Ram Performance to increase your truck's hauling capacity.</p>
                                                <br/>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82215109.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php /*
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img src="<?php echo $url2; ?>catalog/product/8/2/82212951.png" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Genuine Ram Cooler</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>This cooler is designed with outdoor use in mind, suitable for all your adventures.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p;?>sku/82212951.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div> */ ?>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/r/a/ram_2500_82211653.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Storage Bins</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>This genuine OEM Storage Lock will keep your valuables safe and secure in your cab, even when you're not in your truck.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82211653.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="slide-3" class="slid" style="display: none;">
                                <div class="slide">
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82214148.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Bed Extenders</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>This popular Bed Extender connects to the rear of the bed and pivots in and out for extra storage and efficiency.</p>
                                                <br/>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82214148.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/m/o/moparcabinairfilter-jpg_1_1.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Cabin Air Filters</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>This cabin air filter keeps particles like pollen, dust, and sooty exhaust gases out of your vehicle's cabin.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p;?>sku/68406048aa.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215553-a.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Remote Start Kits</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Warm up your truck on a cold winter day, or cool it down on a hot summer day with just the push of a button. A genuine OEM remote start kit from Ram is made to work seamlessly with your vehicle's electronic security key.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82215553.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="slide-4" class="slid" style="display: none;">
                                <div class="slide">
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82215194-a.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Hitches</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Cut your trailer connection time while reducing injuries caused by lifting trailers.</p>
                                                <br/>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82215194.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82213395ab.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Floor Mats</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Genuine OEM floor mats from Ram are made to hug the contours of your truck's footwells for excellent protection against daily wear and tear</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p;?>sku/82213395ab.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82212765-sm.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Air Deflectors</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>This genuine OEM Ram Air Deflector features a wraparound style that helps create an air stream to direct insects and road debris up and away from your truck's hood and windshield.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82212765.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="slide-5" class="slid" style="display: none;">
                                <div class="slide">
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82213499-1_1_.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Roadside Safety Kits</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Be ready for nearly any roadside emergency with this Roadside Safety Kit from Ram.</p>
                                                <br/>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82213499.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/m/o/moparcabinairfilter-jpg_1_2.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Cabin Air Filters</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>This cabin air filter keeps particles like pollen, dust, and sooty exhaust gases out of your vehicle's cabin.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p;?>sku/68169308aa.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82214048.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Fog Lamp Kits</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>If you're going to be out on the road in extreme weather, keep yourself safe with these Ram OEM fog lights.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/82214048.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="slide-6" class="slid" style="display: none;">
                                <div class="slide">
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/t/c/tcfkm526-18-1.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Bike Rack</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Bring your bike along with you on all of your adventures with this low-profile, fork-mount bike carrier by Thule. </p>
                                                <br/>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/tcfkm526ab.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/8/2/82209422ab-17.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Cargo Nets</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>Keep everything in place until you get where you're going. The flexible black cargo net is kept in place using 14 plastic hooks.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p;?>sku/82209422ab.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                                        <div class="card-product">
                                            <div class="card-product-image">
                                                <img class="lazyload" data-src="<?php echo $url2; ?>catalog/product/t/r/trab4553-6.jpg" alt="">
                                            </div>
                                            <div class="card-product-title">
                                                <h5>Roof Racks</h5>
                                            </div>
                                            <div class="card-product-content">
                                                <p>This removable roof rack by Thule enhances your vehicle with sturdy brushed aluminum, multipurpose cross rails.</p>
                                                <div class="card-product-action">
                                                    <a href="<?php echo $p; ?>sku/trab4553.html">LEARN MORE</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage_about_us_banner')->toHtml(); ?>

<div class="spp-banner-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-content')->toHtml(); ?>
            </div>
        </div>
    </div>
</div>
<style>
    .tab-content{
        display: none;
        animation: fadein 1s;

    }

    .tab-content.current{
        display: inherit;


    }
    @keyframes fadein {
        from {
            opacity:1;
        }
        50% {
            opacity: 0;
        }
        to {
            opacity:1;
        }
    }

</style>
<script type="text/javascript">
    var timerInit = setInterval(function(){
        if(typeof jQuery !== 'undefined'){
            jQuery(document).ready(function(){
                jQuery('#shop-cat').detach().insertBefore('.footer-container ');
                jQuery('ul.control-products li').click(function(){
                    var tab_id = jQuery(this).attr('data-tab');

                    jQuery('ul.control-products li').removeClass('current');
                    jQuery('.tab-content').removeClass('current');

                    jQuery(this).addClass('current');
                    jQuery("."+tab_id).addClass('current');
                });
                jQuery('.responsimg').responsImg({
                    allowDownsize: false,
                    elementQuery: false,
                    delay: 250,
                    breakpoints: {
                        mobile: 320,
                        desktop: 960
                    }
                });
            });
            clearInterval(timerInit);
        }
    },200);
</script>
