<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 12/5/16
 * Time: 12:44 AM
 */

class Homebase_Finder_Model_Record extends Mage_Core_Model_Abstract {
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('hfinder/record');
    }
}