<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="container-fluid">
    <div class="cart lfp-inner-md ">
        <div class="page-title title-buttons">
            <?php if(!$this->hasError()): ?>
                <ul class="checkout-types">
                    <?php foreach ($this->getMethods('top_methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                            <li><?php echo $methodHtml; ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <div class="col-sm-12  col-lg-9 lfp-cpr">
            <div class="cart-table-wrap">
                <?php echo $this->getChildHtml('form_before') ?>
                <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
                    <?php echo $this->getBlockHtml('formkey'); ?>
                    <div id="shopping-cart-table" class="data-table cart-table ">
                        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                        <div class="col-md-12 lfp-head lfp-for-desktop no-padding">
                            <div class="col-md-6"><?php echo $this->__('Product Name') ?></div>
                            <?php /* if ($this->helper('wishlist')->isAllowInCart()) : ?>
                                <div class="col-md-2"><?php  $this->__('Move to Wishlist') ?></div>
                                <?php endif  */?>
                            <div class="col-md-2"><?php echo $this->__('Quantity') ?></div>
                            <div class="col-md-2"><?php echo $this->__('Unit Price') ?></div>
                            <div class="col-md-2"><?php echo $this->__('Subtotal') ?></div>
                            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                                <div class="row">
                                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div clas="col-md-12 lfp-body">
                            <?php foreach($this->getItems() as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach ?>
                        </div>
                        <div class="col-md-12 cart-button">
                            <div class="row">
                                <td colspan="50" class="a-right">
                                    <?php if($this->getContinueShoppingUrl()): ?>
                                        <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                                    <?php endif; ?>
                                    <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                                    <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                                    <!--[if lt IE 8]>
                                    <input type="hidden" id="update_cart_action_container" />
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        Event.observe(window, 'load', function()
                                        {
                                            // Internet Explorer (lt 8) does not support value attribute in button elements
                                            $emptyCartButton = $('empty_cart_button');
                                            $cartActionContainer = $('update_cart_action_container');
                                            if ($emptyCartButton && $cartActionContainer) {

                                                Event.observe($emptyCartButton, 'click', function()
                                                {
                                                    $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                                    $cartActionContainer.setAttribute('name', 'update_cart_action');
                                                    $cartActionContainer.setValue('empty_cart');
                                                });
                                            }

                                        });
                                    //]]>
                                    </script>
                                    <![endif]-->
                                </td>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">decorateTable('shopping-cart-table')</script>
                    <script type="text/javascript">
                        //<![CDATA[
                        jQuery(function($){
                            $(".cart .discount h2,.cart .shipping h2").click(function(){
                                if ($(this).hasClass('opened')) {
                                    $(this).removeClass('opened');
                                    $(this).next().slideUp();
                                    $(this).children('.fa').removeClass('fa-chevron-up');
                                    $(this).children('.fa').addClass('fa-chevron-down');
                                } else {
                                    $(this).addClass('opened');
                                    $(this).next().slideDown();
                                    $(this).children('.fa').removeClass('fa-chevron-down');
                                    $(this).children('.fa').addClass('fa-chevron-up');
                                }
                            });
                            })
                                     
                        jQuery( document ).ready(function() { 
                            if(jQuery('#postcode').val()){
                                jQuery('.cart .shipping h2').trigger('click');
                            } 
                        })                        
                       //]]>
                    </script>
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-lg-3 no-padding">
            <div class="cart-collaterals">
                <?php /* Extensions placeholder */ ?>
                <?php echo $this->getChildHtml('checkout.cart.extra') ?>
                <?php echo $this->getChildHtml('coupon') ?>
                <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
                <div class="totals">
                    <h2><?php echo $this->__('Cart Totals') ?></h2>
                    <div>
                        <?php echo $this->getChildHtml('totals'); ?>
                        <?php if(!$this->hasError()): ?>
                            <ul class="checkout-types">
                                <?php foreach ($this->getMethods('methods') as $method): ?>
                                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                                        <li><?php echo $methodHtml; ?></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <?php echo $this->getChildHtml('crosssell') ?>