<style>
.category-products .block-layered-nav .block-content .head {
    width: 100%;
    padding: 10px 15px;
    padding: 10px 15px;
    font-size: 13px!important;
    font-weight: bold;
    text-transform: uppercase;
    position: relative;
    cursor: pointer;
    border-radius: 7px 7px 0 0;
    margin-top: 14px;
    background: #e0a61b!important;
}
.category-products .block-layered-nav .block-content .content ol li span {
    padding-left: 5px;
    font-size: 14px;
    color: #e0a61b;
}

</style>
<div class="row">
<?php echo $this->getChildHtml('product-listing');?>
</div>
