<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 2/24/17
 * Time: 12:00 AM
 */

class Homebase_Autopart_Controller_BaseController extends Mage_Core_Controller_Front_Action{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}