<?php
/**
Made by Smartwave.
 */
?>
<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
$footer = Mage::getStoreConfig('porto_settings/footer',$code);
$oldUrl =  $this->getFormActionUrl();

?>
<style>
    .grecaptcha-badge{
        display:none;
    }
</style>

<div class="block block-subscribe">
    <!-- <div class="block-title">
        <strong><span><?php //echo $footer['footer_newsletter_title']; ?></span></strong>
    </div> -->
    <form action="<?php echo $this->getUrl('news/index/index'); ?>" method="post" id="footer-newsletter-validate-detail">
        <div class="block-content">
            <div class="input-box" style="margin-top:0">
                <!-- <p class="label"><?php //echo $this->__('Enter your e-mail Address'); ?></p> -->
                <input type="text" name="email" id="newsletter_footer" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text" placeholder="email@email.com" />
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span style="padding:0 15px"><span><?php echo $this->__('Subscribe') ?></span></span></button>
                <div class="clearer"></div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        (function($){
            $(document).ready(function(){
                var form = $('#footer-newsletter-validate-detail');
                var url = $(form).attr('action');
                var input = $('#newsletter_footer');
                var parent = input.parent();
                var isEnableCaptcha = '<?php echo Mage::helper('growthrocket_gtm/captcha')->isEnableCaptchaCategory('newsletter') ?>';
                $(form).on('submit',function(evt){
                    var emailVal = $(input).val();
                    evt.preventDefault();

                    if(emailVal === '') {
                        messagehandler(parent, 'error','Please enter a valid email address.');
                        return;
                    }

                    if(isEnableCaptcha) {
                        grecaptcha.ready(function() {
                            grecaptcha.execute('<?php echo Mage::helper('growthrocket_gtm/captcha')->getSiteKey() ?>', {action: 'submit_newsletter'}).then(function(token) {
                                subscribeNewsletter(emailVal, parent, url, token);
                            });
                        });
                    }else {
                        subscribeNewsletter(emailVal, parent, url, '');
                    }

                });
            });

            function subscribeNewsletter(emailVal, parent, url, token)
            {
                if(validateEmail(emailVal)){
                    $.ajax({
                        url: url,
                        data: {email: emailVal, token:token},
                        method: 'post',
                        complete: function(response, textStatus){
                            var res = jQuery.parseJSON(response.responseText);
                            if(textStatus == 'success') {
                                messagehandler(parent, 'success','Success! You\'ve been signed up!');
                            }else {
                                messagehandler(parent, 'error',res.msg);
                            }
                        }
                    });
                }else{
                    messagehandler(parent, 'error','Please enter a valid email address.');
                }
            }

            function messagehandler(parentEl,msgType,text){
                var message = $("<p/>");
                if($(parentEl).prev('p').length > 0){
                    message = $(parentEl).prev('p');
                }
                $(message).html(text);
                $(message).attr('class', msgType);
                $(message).insertBefore(parentEl);
            }
        })(jQuery);
        function ajaxNewsletter(){
            return false;
        }
        function validateEmail(v){
            return Validation.get('IsEmpty').test(v) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(v);
        }
    </script>
</div>
