<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 4/2/17
 * Time: 7:02 PM
 */

/** @var Homebase_Autopart_Block_Display_List $this */
$list = $this->getList();
$rowCount = 0;
$flag = 0;

$subtitle = "";
if(strpos(Mage::helper('core/url')->getCurrentUrl(), '/make/') !== false) {
    $subtitle = "Pick your vehicle’s model from the selection below:";
} else if (strpos(Mage::helper('core/url')->getCurrentUrl(), '/model/') !== false) {
    $subtitle = "Please select your vehicle's year below:";
} else if (strpos(Mage::helper('core/url')->getCurrentUrl(), '/year/') !== false) {
    $subtitle = "Here are the available accessories for your vehicle:";
}

$request = $this->getRequest();
$requestString = $request->getRequestString();
$requestSegments = array_filter(explode('/', $requestString));

$blockowner = str_replace('.html','',end($requestSegments));
$titlePrefix = "";
if($request->getActionName() == 'model') {
    $titlePrefix = '&nbsp;Parts & Accessories';
}
?>
    <!--YMM FORM -->

<?php if(count($list) > 0): ?>

<?php
if (strpos(Mage::helper('core/url')->getCurrentUrl(), '/model/') !== false) { ?>

<?php } ?>
    <div class="container">
        <h1> <?php echo $this->getAutoName() . $titlePrefix; ?></h1>
        <div class="listing-top-text">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing-top-' . $blockowner)->toHtml(); ?>
        </div>
        <?php if (!empty($subtitle)) : ?>
        <p style="text-align:left;"><?php echo $subtitle; ?></p>
        <?php endif; ?>
        <div id="weekly_featured_product">
            <div class="row product-list-container">
                <?php foreach ($list as $item): ?>
      
                    <?php if($this instanceof Homebase_Autopart_Block_Category_Model):?>
                            <div class="col-xs-12 col-sm-6 col-md-3">
                                   
                     <?php else: ?>
                            <div class="col-xs-12 col-sm-6 col-md-3">
                     <?php endif; ?>
                        <div class="product-item-container">
                                 <?php if($this instanceof Homebase_Autopart_Block_Category_Model):?>
                                     <a href="<?php echo $this->getCustomLink($item->getLabel()); ?>">
                                     <?php echo $item->getLabel(); ?>
                                     <?php echo $this->getAutoName(); ?>
                                     <i class="fa fa-angle-right" style="float: right;font-size: 24px;"></i>
                                    </a>
                                 <?php else: ?>
                                    <a href="<?php echo $this->getCustomLink($item->getLabel()); ?>"><?php echo $item->getName(); ?><i class="fa fa-angle-right" style="float: right;font-size: 24px;"></i></a>
                                 <?php endif; ?>  

                        </div>
                         
                    </div>

                <?php endforeach; ?>
            </div>
        </div>
        <div class="listing-bottom-text">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing-bottom-' . $blockowner)->toHtml(); ?>
        </div>
    </div>
  <script type="text/javascript">
        jQuery(document).ready(function(){

            jQuery('img').imageFallback(['<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>category/model-watermark.png']);

        });
    </script>

    
<?php else: ?>
    <div class="std">
        <h1 style="text-align:center;margin: 20px 0; font-size: 70px;margin-top:70px">No Product Found<i class="icon-doc"></i></h1>
        <p style="text-align:center; font-size: 15px;">Please select another category that have products.</a></p>
    </div>
<?php endif; ?>