<?php
    $collection = $this->collection();
    if(!empty($collection)):
$counter = 0;
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
$path = $url->getPath();

$action =  $this->getRequest()->getActionName();

?>
<?php if($action == "model"): ?>
<div class="category-part-listing accordion" id="partnameAccordion">
    <?php foreach ($collection as $category =>  $partCollection): ?>
    <?php
        $counter++;
        $partId =  uniqid();
    ?>

    <div class="part-header collapsed"  data-toggle="collapse" data-target="#<?php echo $partId; ?>" data-parent="#partnameAccordion" aria-controls="<?php echo $partId; ?>">
        <span><?php echo $category ?></span>
        <span class="icon plus"><i class="fa fa-plus"></i></span>
        <span class="icon minus"><i class="fa fa-minus"></i> </span>
    </div>
    <?php
    if(Mage::helper('hautopart')->getSortPartName() ==  'alphabetical') {
        ksort($partCollection);
    }
    $innerCounter = 1;
    $totalPart = count($partCollection);
    ?>
    <div class="wrapper cat-owl-wrapper collapse" id="<?php echo $partId ?>" data-custom-nav="<?php echo 'pn' . $partId ?>" aria-labelledby="<?php echo $partId; ?>" data-parent="#partnameAccordion">

        <?php if(count($partCollection) > 10): ?>
        <div class="cat-list owl-carousel">
            <?php foreach ($partCollection as $partname => $partData): ?>
            <?php if($innerCounter == 1): ?>
                <div class="part-item">
            <?php endif; ?>
                   <div class="inner-item">
                       <a class="link image-container" href="<?php echo $partData['link'] ?>">
                           <img class="lazyload"  data-src="<?php echo $partData['image_url'] ?>"/>
                       </a>
                       <a class="link title" href="<?php echo $partData['link'] ?>"><?php echo $partData['name'] ?></a>
                   </div>
                <?php if($innerCounter % 2 == 0 && $innerCounter <= $totalPart): ?>
                    </div>
                    <div class="part-item">
                <?php endif; ?>
                 <?php $innerCounter++ ?>
                <?php if($innerCounter > $totalPart): ?>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
                     
        </div>
        
        <?php else: ?>
           <div class="cat-list-new onerow">
               <?php foreach ($partCollection as $partname => $partData): ?>
                   <div class="part-item col-md-5ths col-sm-4 col-md-3">
                       <a class="link image-container" href="<?php echo $partData['link'] ?>">
                           <img class="lazyload" data-src="<?php echo $partData['image_url'] ?>"/>
                       </a>
                    
                       <a class="link title" href="<?php echo $partData['link'] ?>"><?php echo $partData['name'] ?></a>
                   </div>
               <?php endforeach; ?>
           </div>

        <?php endif; ?>
        
       
     
           <div class="col-sm-12 text-center">
               <a href="<?php echo $this->getCategoryUrl($category) ?>" class="button part-button"><?php echo $this->__('Browse Category') ?></a>
           </div>
    </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
  jQuery(document).ready(function() {
    var owl = jQuery(".cat-list");
    owl.owlCarousel({
      margin: 10,
      pagination: false,
      itemsDesktop : [1499,5],
      itemsDesktopSmall : [1199,5],
      itemsTablet : [899,2],
      itemsMobile : [599,1],
      navigation : true,
      navigationText : ['<span class="fa-stack"><i class="fa fa-caret-left"></i></span>','<span class="fa-stack"></i><i class="fa fa-caret-right"></i></span>'],

  });
if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
 // some code..
 var owl = jQuery(".onerow");
        owl.owlCarousel({
          margin: 10,
          pagination: false,
          itemsDesktop : [1499,5],
          itemsDesktopSmall : [1199,5],
          itemsTablet : [899,2],
          itemsMobile : [599,1],
          navigation : true,
          navigationText : ['<span class="fa-stack"><i class="fa fa-caret-left"></i></span>','<span class="fa-stack"></i><i class="fa fa-caret-right"></i></span>'],

      });
}

});

</script>
<?php else: ?>
<!-- -->
<div class="category-part-listing">
    <?php foreach ($collection as $category =>  $partCollection): ?>
    <h2><?php echo $category ?></h2>
        <?php
        if(Mage::helper('hautopart')->getSortPartName() ==  'alphabetical') {
            ksort($partCollection);
        }

        $loadMore = false;
        $part1Collection = $partCollection;
        $defaultNo = 10;
        if(count($partCollection) >$defaultNo) {
            $part1Collection = array_slice($part1Collection, 0,$defaultNo, true);
            $part2Collection = array_slice($partCollection, $defaultNo, count($partCollection),true);
            $loadMore = true;
        }
        ?>
    <div class="wrapper" data-more-items="<?php echo htmlentities(json_encode($part2Collection)) ?>">
        <div class="row cat-list">
            <?php foreach ($part1Collection as $partname => $partData): ?>
                <div class="part-item col-md-5ths col-sm-4 col-md-3">
                    <a class="link image-container" href="<?php echo $partData['link'] ?>">
                    <img src="<?php echo $partData['image_url'] ?>"/>
                    </a>
                    <a class="link title" href="<?php echo $partData['link'] ?>"><?php echo $partData['name'] ?></a>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if($loadMore): ?>
            <div class="button-container"><button class="button show" data-status="more"><?php echo $this->__('Show More') ?></button></div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php endif; ?>

