<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 4/2/17
 * Time: 7:02 PM
 */

/** @var Homebase_Autopart_Block_Display_List $this */
$list = $this->getList();
$rowCount = 0;
$flag = 0;

$subtitle = "";
if(strpos(Mage::helper('core/url')->getCurrentUrl(), '/make/') !== false) {
    $subtitle = "Select your vehicle's Model below";
} else if (strpos(Mage::helper('core/url')->getCurrentUrl(), '/model/') !== false) {
    $subtitle = "Select your vehicle's year below";
} else if (strpos(Mage::helper('core/url')->getCurrentUrl(), '/year/') !== false) {
    $subtitle = "Here are the available accessories for your vehicle";
}

$request = $this->getRequest();
$requestString = $request->getRequestString();
$requestSegments = array_filter(explode('/', $requestString));

$blockowner = str_replace('.html','',end($requestSegments)); 
?>
    <!--YMM FORM -->

<?php if(count($list) > 0): ?>

<?php
if (strpos(Mage::helper('core/url')->getCurrentUrl(), '/model/') !== false) { ?>

<?php } ?>
    <div class="fluid-container lfp-shop-year">
        <div class="lfp-inner-lg">
            <div class="listing-top-text">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing-top-' . $blockowner)->toHtml(); ?>
        </div>
        <?php if (!empty($subtitle)) : ?>
        <h2 class="lfp-subtitle"><?php echo $subtitle; ?></h2>
        <?php endif; ?>
        <div id="weekly_featured_product">
            <div class="row product-list-container">
                <?php foreach ($list as $item): ?>

                    <?php if($this instanceof Homebase_Autopart_Block_Category_Model):?>
                            <div class="col-xs-12 col-sm-6 col-md-3 custom-padding">

                     <?php else: ?>
                            <div class="col-xs-12 col-sm-6 col-md-3 custom-padding">
                     <?php endif; ?>
                        <div class="product-item-container">
                                 <?php if($this instanceof Homebase_Autopart_Block_Category_Model):?>
                                    <a class="product-part-link" href="<?php echo $this->getCustomLink($item->getLabel()); ?>">
                                        <div class="lfp-text-container">
                                             <?php echo $item->getLabel(); ?>
                                            <?php echo $this->getAutoName(); ?>
                                        </div>
                                        <div class="icon"><i class="fa fa-chevron-right"></i></div>
                                    </a>
                                 <?php else: ?>
                                    <a class="product-part-link" href="<?php echo $this->getCustomLink($item->getLabel()); ?>">
                                        <div class="lfp-text-container">
                                             <?php echo $item->getLabel(); ?>
                                        </div>
                                        <div class="icon"><i class="fa fa-chevron-right"></i></div>
                                    </a>
                                 <?php endif; ?>

                        </div>

                    </div>

                <?php endforeach; ?>
            </div>
        </div>
        <div class="listing-bottom-text">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing-bottom-' . $blockowner)->toHtml(); ?>
        </div>
        </div>
    </div>
  <script type="text/javascript">
        jQuery(document).ready(function(){

            jQuery('.product-list-container img').imageFallback(['<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>category/model-watermark.png']);

        });
    </script>

    
<?php else: ?>
    <div class="std">
        <h1 style="text-align:center;margin: 20px 0; font-size: 70px;margin-top:70px">No Product Found<i class="icon-doc"></i></h1>
        <p style="text-align:center; font-size: 15px;">Please select another category that have products.</a></p>
    </div>
<?php endif; ?>