

<div class="fluid-container lfp-shop-category" id="shop-category">
    <div class="lfp-inner-lg">
        <div class="col-lg-3 col-sm-12">
            <div class="col-sm-8">
                <h2>Shop By Category</h2>
            </div>
        </div>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_static_category')->toHtml(); ?>
        <div  class="lfp-clear" ></div>
    </div>
</div>



