<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 1/23/18
 * Time: 10:50 PM
 */
?>
<div class="footer-shop-category">
    <div class="footer-shop-category-title">
        <h2>Shop By Category</h2>
    </div>
    <div class="footer-shop-category-content">
        <ul>
            <li>
                <a href="http://devsop.allmoparparts.com/category/interior-accessories.html">
                    <div class="footer-shop-element">
                        <img src="<?php echo $this->getSkinUrl('images/hp/interior_accessories.jpg'); ?>" alt="">
                        <p>Interior</p>
                        <p>Accessories</p>
                    </div>
                </a>
            </li>
            <li>
                <a href="http://devsop.allmoparparts.com/category/exterior-accessories.html">
                    <div class="footer-shop-element">
                        <img src="<?php echo $this->getSkinUrl('images/hp/exterior_accessories.jpg'); ?>" alt="">
                        <p>Exterior</p>
                        <p>Accessories</p>
                    </div>
                </a>
            </li>
            <li>
                <a href="http://devsop.allmoparparts.com/category/audio-and-media-accessories.html">
                    <div class="footer-shop-element">
                        <img src="<?php echo $this->getSkinUrl('images/hp/audio_media_accessories.jpg'); ?>" alt="">
                        <p>Audio & Media</p>
                        <p>Accessories</p>
                    </div>
                </a>
            </li>
            <li>
                <a href="http://devsop.allmoparparts.com/category/racking-accessories.html">
                    <div class="footer-shop-element">
                        <img src="<?php echo $this->getSkinUrl('images/hp/racking_accessories.jpg'); ?>" alt="">
                        <p>Racking</p>
                        <p>Accessories</p>
                    </div>
                </a>
            </li>
            <li>
                <a href="http://devsop.allmoparparts.com/category/maintenance-parts.html">
                    <div class="footer-shop-element">
                        <img src="<?php echo $this->getSkinUrl('images/hp/maintenance_parts.jpg'); ?>" alt="">
                        <p>Maintenance</p>
                        <p>Parts</p>
                    </div>
                </a>
            </li>
            <li>
                <a href="#">
                    <div class="footer-shop-element">
                        <img src="<?php echo $this->getSkinUrl('images/hp/gear_gift_ideas.jpg'); ?>" alt="">
                        <p>Gear & Gift</p>
                        <p>Ideas</p>
                    </div>
                </a>
            </li>
        </ul>
    </div>
</div>

