<div id="slideshow" style="background:none; height:80px; position:relative;">
    <div class="ymm-form-container">
        <div class="container">
            <div class="row">
                <div class="ymm-content">
                    <form action="<?php echo $this->getUrl('amfinder/index/search'); ?>" method="post" id="finderForm" class="floating">
                        <style>
                            #finderForm.floating {
                                position:absolute; left:0;background:#369ED3; padding-bottom:10px
                            }
                            #slideshow form .form-fields-container,
                            #slideshow .ymm-label {
                                display: none;
                                text-align: center
                            }
                        </style>
                        <div class="container partfinder-result text-center">
                            <span class="partfinder-selector">
                                <span class="selections">{{ YEAR }}</span>
                                <span class="selections">{{ MAKE }}</span>
                                <span class="selections">{{ MODEL }}</span>
                            </span>
                        </div>
                        <button class="button finder-reset" name="reset" value="1" title="Reset" type="submit"><span><span>Reset</span></span></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>