<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 7/4/17
 * Time: 11:29 PM
 */
?>
<div class="row">
    <div class="col-md-12">
        <?php echo $this->getChildHtml('product-listing');?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div id="parts-related-container">
            <?php echo $this->getChildHtml('parts-related'); ?>
        </div>
    </div>
</div>