<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 10/8/18
 * Time: 3:59 PM
 */

class Growthrocket_Content_Block_Content_Part_Model extends Growthrocket_Content_Block_Content{
    const FITMENT_PARAM_PART_MAKE = 'partmodel';

    private $fitment = array();

    protected function _construct(){
        parent::_construct();
    }

    protected function _beforeToHtml()
    {
        $this->fitment = $this->getFitmentParams();
        $requestPath = substr($this->getRequest()->getRequestString(),1);
        $storeId = Mage::app()->getStore()->getId();
        $contentId = $this->sqlHelper->getPageContent($requestPath, self::FITMENT_PARAM_PART_MAKE, $storeId);

        if($contentId){
            $this->setId($contentId);
        }else{
            $defaultContentId = Mage::getStoreConfig('grcontent/makemodel/content');
            $this->setId($defaultContentId);
        }

        return $this; // TODO: Change the autogenerated stub
    }

    protected function getTemplateProcessor()
    {
        $processor = $this->helper->getPartModelTemplateProcessor();

        $processor->setFitment($this->fitment);
        return $processor;
    }
}