<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 9/5/18
 * Time: 1:27 PM
 */

class Growthrocket_Html_Model_Resource_Page_Collection extends Mage_Core_Model_Mysql4_Collection_Abstract{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('grhtml/page');
    }
}