<?php $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>
<div id="top-cat">
   <div class="container">
      <div class="row">
         <div class="col-sm-12 col-xs-12">
            <h2>Top Selling Categories</h2>
         </div>
      </div>
      <div class="row">
         <div class="col-md-4 col-sm-12 col-xs-12 ">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_interior.jpg"  data-responsimg320="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_interior.jpg"
        data-responsimg480="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_interior.jpg"
        data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_interior.jpg"/>
            <div class="text-img bottom-left">
               <h4><a href="/category/interior-accessories.html">Interior Accessories</a></h4>
               <ul>
                  <li><a href="/part/armrest-extension.html">Armrest Extension</a></li>
                  <li><a href="/part/handbrake-lever.html">Handbrake Lever</a></li>
                  <li><a href="/part/pedal-set.html">Pedal Set</a></li>
                  <li><a href="/part/mobile-wifi.html">Mobile WiFi</a></li>
               </ul>
            </div>
            <div class="space"></div>
         </div>
         <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="row">
               <div class="col-sm-12 col-xs-12">
                  <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_exterior.jpg" data-responsimg320="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_exterior.jpg"
        data-responsimg480="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_exterior.jpg"
        data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_exterior.jpg"/>
                  <div class="text-img top-left">
                     <h4><a href="/category/exterior-accessories.html">Exterior Accessories</a></h4>
                      <ul>
                          <li><a href="<?php echo $url ?>part/emblem.html">Emblem</a></li>
                          <li><a href="<?php echo $url ?>part/license-plate-bracket.html">License Plate Bracket</a></li>
                          <li><a href="<?php echo $url ?>part/wheel-cap.html">Wheel Cap</a></li>
                          <li><a href="<?php echo $url ?>part/roof-rack.html">Roof Rack</a></li>
                      </ul>
                  </div>
               </div>
               <div class="space"></div>
               <div class="col-sm-12 col-xs-12">
                  <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_audio.jpg"  data-responsimg320="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_audio.jpg"
        data-responsimg480="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_audio.jpg"
        data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_audio.jpg"/>
                  <div class="text-img top-left">
                     <h4 style="width: 100%"><a href="/category/remote-start-electronics-and-audio-accessories.html">Audio & Media Accessories</a></h4>
                      <ul>
                          <li><a href="<?php echo $url ?>part/audio-hub.html">Audio Hub</a></li>
                          <li><a href="<?php echo $url ?>part/headphones.html">Headphones</a></li>
                          <li><a href="<?php echo $url ?>part/audio-jack.html">Audio Jack</a></li>
                          <li><a href="<?php echo $url ?>part/bluetooth.html">Bluetooth</a></li>
                      </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="container">
      <div class="row">
         <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="row">
               <div class="col-sm-12 col-xs-12">
                  <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_performance.jpg"  data-responsimg320="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_performance.jpg"
        data-responsimg480="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_performance.jpg"
        data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_performance.jpg"/>
                  <div class="text-img top-right">
                     <h4><a href="/category/subaru-performance-parts.html">Performance Parts</a></h4>
                      <ul>
                          <li><a href="<?php echo $url ?>part/heat-shield.html">Heat Shield</a></li>
                          <li><a href="<?php echo $url ?>part/transmission-mount.html">Transmission Mount</a></li>
                          <li><a href="<?php echo $url ?>part/bushing.html">Bushing</a></li>
                          <li><a href="<?php echo $url ?>part/chassis-brace.html">Chassis Brace</a></li>
                      </ul>
                  </div>
               </div>
               <div class="space"></div>
               <div class="col-sm-12 col-xs-12">
                  <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_racking.jpg" data-responsimg320="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_racking.jpg"
        data-responsimg480="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_racking.jpg"
        data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_racking.jpg"/>
                  <div class="text-img top-right">
                     <h4><a href="/category/cargo-towing-and-racking-accessories.html">Racking Accessories</a></h4>
                      <ul>
                          <li><a href="<?php echo $url ?>part/ball-mount.html">Ball Mount</a></li>
                          <li><a href="<?php echo $url ?>part/hitch-plug.html">Hitch Plug</a></li>
                          <li><a href="<?php echo $url ?>part/portable-step.html">Portable Step</a></li>
                          <li><a href="<?php echo $url ?>part/trailer-hitch-adapter.html">Trailer Hitch Adapter</a></li>
                      </ul>
                  </div>
               </div>
               <div class="space"></div>
            </div>
         </div>
         <div class="col-md-4 col-sm-12 col-xs-12 ">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_maintenance.jpg"  data-responsimg320="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_maintenance.jpg"
        data-responsimg480="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/spp_m_home_maintenance.jpg"
        data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_maintenance.jpg"/>
            <div class="text-img bottom-right">
               <h4><a href="/category/tuneup-and-maintenance-parts.html">Maintenance Parts</a></h4>
               <ul>
                  <li><a href="/part/headlamp.html">Headlamp</a></li>
                  <li><a href="/part/rain-guards.html">Rain Guards</a></li>
                  <li><a href="/part/door-edge-guards.html">Door Edge Guards</a></li>
                  <li><a href="/part/license-plate-frame.html">License Plate Frame</a></li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</div>

<div id="feat-model">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('feat-model')->toHtml(); 
                ?> 
            </div>
        </div>
    </div>
</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('must_have_for_your_car')->toHtml(); ?>
<div id="spp-banner">
   <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_banner.jpg" width="100%;"  data-responsimg320="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/SPP_Banners_768x548_02.jpg"
        data-responsimg480="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/responsive/SPP_Banners_768x548_02.jpg" data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_banner.jpg"/>
   <div class="container">
      <div class="row">
         <div class="col-sm-12 col-xs-12">
            <div class="spp-banner-text">
               <h4>WE ARE AN</h4>
               <h2>Authorized Factory Retailer of Subaru Parts</h2>
            </div>
         </div>
      </div>
   </div>
</div>
<div class="spp-banner-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-content')->toHtml(); ?>
            </div>
        </div>
    </div>
</div>

<?php echo Mage::app()->getLayout()->createBlock('gr_bestseller/collection')->setTemplate('bestseller/list.phtml')->toHtml(); ?>
<div id="featured-product">
<div class="container">
   <div class="row">
      <div class="col-sm-12 col-xs-12">
         <h2>Featured Products</h2>
         <ul class="control-products">
            <li class="current" data-tab="tab1"><span class="none">Popular</span> Impreza <span class="none">Parts</span></li>
            <li data-tab="tab2"><span class="none">Popular</span> Forester <span class="none">Parts</span></li>
            <li data-tab="tab3"><span class="none">Popular</span> Legacy <span class="none">Parts</span></li>
         </ul>
      </div>
   </div>
   <div class="tab1 tab-content current">
      <div class="row">
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_impreza_illumination.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_impreza_illumination.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Interior 
                  Illumination Kit
               </h4>
               <p>
                 For a custom, personalized interior, install a genuine OEM footwell illumination kit from Subaru.
               </p>
               <a href="/sku/h461sfl000.html">Learn More</a>
            </div>
         </div>
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_impreza_shift_knob.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_impreza_shift_knob.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Shift Knob</h4>
               <p>
                  5 M/T - STI - If you're looking for some STI-inspired flair for your Subaru Impreza, this is just the touch you've been looking for. This STI-style...
               </p>
               <a href="/sku/c1010fg000.html">Learn More</a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-12">
            <div class="space"></div>
         </div>
      </div>
      <div class="row">
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_filter.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_filter.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Air 
                Filter
               </h4>
               <p>Genuine Subaru Original replacement air filter for your Impreza.</p>
               <a href="/sku/16546aa12a.html">Learn More</a>
            </div>
         </div>
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_cargo.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_cargo.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Cargo Organizer</h4>
               <p>This genuine OEM cargo organizer from Subaru conveniently transports your outdoor gear or your grocery bags, and quickly collapses for easy storage.</p>
               <a href="/sku/soa567t100.html">Learn More</a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-12 margin-button">
            <a class="button button-blue" href="/model/subaru-impreza.html">VIEW ALL IMPREZA PARTS</a>
         </div>
      </div>
   </div>

<!-- -->
   <div class="tab2 tab-content">
      <div class="row">
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_forester_center_console.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_forester_center_console.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Center Console Upgrade Kit
               </h4>
               <p>
                  This leather center console upgrade kit from Subaru will add a stylish touch to your Forester's interior. Easy installation. 
               </p>
               <a href="/sku/forcenconkit.html">Learn More</a>
            </div>
         </div>
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_forester_throw_shift.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_forester_throw_shift.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Short Throw Shifter
               </h4>
               <p>
                 Significantly reduces shift throw lengths for crisper shifts and a sportier driving feel.
               </p>
               <a href="/sku/c1010sc100.html">Learn More</a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-12">
            <div class="space"></div>
         </div>
      </div>
      <div class="row">
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_forester_wipers.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_forester_wipers.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Wiper Blades
               </h4>
               <p>Superior, all-weather performance - innovative Memory Curve Steel beam design Infinite number of pressure points compared to ordinary wiper...</p>
               <a href="/sku/soa591b619-soa591b622.html">Learn More</a>
            </div>
         </div>
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_filter.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_filter.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Air Filter</h4>
               <p>Genuine Subaru Original replacement air filter for your Forester.</p>
               <a href="/sku/16546aa12a.html">Learn More</a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-12 margin-button">
            <a class="button button-blue" href="/model/subaru-forester.html">VIEW ALL Forester Parts</a>
         </div>
      </div>
   </div>

   <div class="tab3 tab-content">
      <div class="row">
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_cargo.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_cargo.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Cargo Organizer
               </h4>
               <p>
                 This genuine OEM cargo organizer from Subaru conveniently transports your outdoor gear or your grocery bags, and quickly collapses for easy storage.
               </p>
               <a href="/sku/soa567t100.html">Learn More</a>
            </div>
         </div>
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_legacy_molding.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_legacy_molding.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Body Side Molding Kit
               </h4>
               <p>
                  Painted to match, OEM quality, Body Side Molding Kits protect your Subaru Outback from shopping carts, door dings, scratches and other road hazards....
               </p>
               <a href="/sku/j101sal802-.html">Learn More</a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-12">
            <div class="space"></div>
         </div>
      </div>
      <div class="row">
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_legacy_sparkplug.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_legacy_sparkplug.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Spark Plugs
               </h4>
               <p>22401AA751 Spark plugs. Several fitments for 6 cylinder 3.6L engines. Set of 6. Please be sure to include your vin number in the order notes so we...</p>
               <a href="/sku/6x-22401aa751.html">Learn More</a>
            </div>
         </div>
         <div class="col-md-6 col-sm-12 col-xs-12">
            <img class="responsimg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_filter.jpg"  data-responsimg-desktop="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>home/spp_filter.jpg"/>
            <div class="text-img-p">
               <h4>Subaru Air Filter</h4>
               <p>Genuine Subaru Original replacement air filter for your Legacy.</p>
               <a href="/sku/16546aa12a.html">Learn More</a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-12 margin-button">
            <a class="button button-blue" href="/model/subaru-legacy.html">VIEW ALL Legacy Parts</a>
         </div>
      </div>
   </div>

</div>
<style>
        ul.control-products li.current{
            color: black;
        }

        .tab-content{
            display: none;
          animation: fadein 1s;
        
        }

        .tab-content.current{
            display: inherit;
            

        }    
@keyframes fadein {
  from {
    opacity:1;
  }
  50% {
    opacity: 0;
  }
  to {
    opacity:1;
  }
}

</style>
<script type="text/javascript">
    var timerInit = setInterval(function(){
        if(typeof jQuery !== 'undefined'){
            jQuery(document).ready(function(){
                jQuery('#shop-cat').detach().insertBefore('.footer-container ');
                jQuery('ul.control-products li').click(function(){
                    var tab_id = jQuery(this).attr('data-tab');

                    jQuery('ul.control-products li').removeClass('current');
                    jQuery('.tab-content').removeClass('current');

                    jQuery(this).addClass('current');
                    jQuery("."+tab_id).addClass('current');
                });
                jQuery('.responsimg').responsImg({
                    allowDownsize: false,
                    elementQuery: false,
                    delay: 250,
                    breakpoints: {
                        mobile: 320,
                        desktop: 960
                    }
                });
            });
            clearInterval(timerInit);
        }
    },200);
</script>
