<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Finder
 */

$amFinder = Mage::getSingleton('catalog/session')->getAmfinder_1();
$hFinder = Mage::getSingleton('core/session')->getHFinder_1();
$category = Mage::registry('current_category');
?>

<?php $finderId = 'amfinder_' . uniqid(); ?>
<form method="post" action="<?php echo $this->getActionUrl() ?>" id="finderForm" class="floating">
<?php if ($category !=null && Mage::getBlockSingleton('page/html_header')->getIsHomePage() === false && ($category->getParentId() && $category->getParentId() == 1)) : ?>
    <?php if($amFinder) : ?>
    <style>
    #finderForm.floating {
        position:absolute; left:0;background:#369ED3; padding-bottom:10px
    }
    #slideshow form .form-fields-container,
    #slideshow .ymm-label {
        display: none;
        text-align: center
    }
    </style>
    <div class="container partfinder-result text-center">
        <span><?php echo $this->__('Your Vehicle'); ?>: </span>
        <span class="partfinder-selected">
            <?php
                foreach ($amFinder AS $key => $value) :
                    if (is_numeric($key)) :
                        $valueResult = Mage::getModel('amfinder/value')->load($value);
            ?>
                <span class="selections"><?php echo $valueResult['name']; ?></span>
            <?php
                    endif;
                endforeach;
            ?>
        </span>
        <button class="button" onclick="jQuery('#finderForm').removeClass('floating'); jQuery('.partfinder-result').hide(); jQuery('#slideshow form .form-fields-container, #slideshow .ymm-label').show(); return false;" style="margin-left:13px"><span><span><?php echo $this->__('Change') ?></span></span></button>
        <button class="button finder-reset" name="reset" value="1" title="<?php echo $this->__('Reset') ?>" type="submit"><span><span><?php echo $this->__('Reset') ?></span></span></button>
    </div>
    <?php else: ?>
        <!-- <script type="text/javascript">window.location.href="<?php echo Mage::getBaseUrl(); ?>";</script> -->
    <?php endif; ?>
<?php endif; ?>
    <?php if(is_array($hFinder) && count($hFinder) > 0) :?>
            <?php $amFinder = $hFinder; ?>
            <style>
            #finderForm.floating {
                position:absolute; left:0;background:#369ED3; padding-bottom:10px
            }
            #slideshow form .form-fields-container,
            #slideshow .ymm-label {
                display: none;
                text-align: center
            }
            </style>
            <div class="container partfinder-result text-center">
                <span><?php echo $this->__('Your Vehicle'); ?>: </span>
                <span class="partfinder-selected">
                    <?php
                        foreach ($amFinder AS $key => $value) :
                            if (is_numeric($key)) :
                                $valueResult = Mage::getModel('amfinder/value')->load($value);
                    ?>
                        <span class="selections"><?php echo $valueResult['name']; ?></span>
                    <?php
                            endif;
                        endforeach;
                    ?>
                </span>
                <button class="button" onclick="jQuery('#finderForm').removeClass('floating'); jQuery('.partfinder-result').hide(); jQuery('#slideshow form .form-fields-container, #slideshow .ymm-label').show(); return false;" style="margin-left:13px"><span><span><?php echo $this->__('Change') ?></span></span></button>
                <button class="button finder-reset" name="reset" value="1" title="<?php echo $this->__('Reset') ?>" type="submit"><span><span><?php echo $this->__('Reset') ?></span></span></button>
            </div>
        <?php endif; ?>
    <div class="form-fields-container">
        <input type="hidden" name="finder_id" value="<?php echo $this->getId() ?>"/>
        <input type="hidden" name="back_url" value="<?php echo $this->getBackUrl() ?>"/>
        <input type="hidden" name="category_id" value="<?php echo $this->getCurrentCategoryId() ?>"/>
        <div class="amfinder-responsive" id="<?php echo $finderId ?>Container">
            <div class="amfinder-title">
                <span><?php echo $this->getFinder()->getName() ?></span>
            </div>
            <ul class="amfinder-toggle">
                <?php foreach ($this->getFinder()->getDropdowns() as $dropdown): ?>
                    <li>
                        <div class="dropdown-title"><?php echo $this->__($this->htmlEscape($dropdown->getName())) ?></div>
                        <div class="dropdown-element amshopby-clearer">
                            <select <?php echo $this->getDropdownAttributes($dropdown)?>" data-name="<?php echo $this->__($this->htmlEscape($dropdown->getName())) ?>">
                                <option value="0">Select <?php echo $this->__($this->htmlEscape($dropdown->getName())) ?></option>
                                <?php foreach($this->getDropdownValues($dropdown) as $v): ?>
                                    <?php if($v['value'] != 0): ?>
                                    <option value="<?php echo $v['value'] ?>"<?php if ($v['selected'] && (Mage::getBlockSingleton('page/html_header')->getIsHomePage() === false )):?>selected="selected"<?php endif ?>>
                                        <?php echo $this->htmlEscape($v['label']) ?>
                                    </option>
                                    <?php endif; ?>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </li>
                <?php endforeach ?>
                <li class="last">
                    <div class="amfinder-buttons" >
                        <button class="button" title="<?php echo $this->__('Shop Now') ?>" type="submit" <?php echo ($this->isButtonsVisible() ? '' : 'disabled="disabled"')?>><span><span><?php echo $this->__('Shop Now') ?></span></span></button>
                        <!-- <button class="button" title="<?php echo $this->__('Find') ?>" type="submit"><span><span><?php echo $this->__('Find') ?></span></span></button> -->
                        <!-- <button class="button" name="reset" value="1" title="<?php echo $this->__('Reset') ?>" type="submit"><span><span><?php echo $this->__('Reset') ?></span></span></button> -->
                    </div>
                </li>
            </ul>
        </div>
    </div>
</form>
<script type="text/javascript">
    var <?php echo $finderId ?>  = new amFinder(
        '<?php echo $finderId ?>Container',
        '<?php echo $this->getAjaxUrl() ?>',
        '<?php echo $this->__('Loading...')?>',
        '<?php echo Mage::getStoreConfig('amfinder/general/partial_search')?>',
        <?php echo intval(Mage::getStoreConfig('amfinder/general/auto_submit')) ?>
    );


    jQuery('.amfinder-title').unbind('click');
    jQuery('.amfinder-title').click(function(event){
        var block = jQuery(this).parent();
        if (block.hasClass('open')) {
            block.removeClass('open');
        } else {
            block.addClass('open');
        }
    });
</script>
<br />