<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 1/24/18
 * Time: 7:29 AM
 */
$imgPath = $this->getImage();
?>
<div class="product-item-container sop-product-item-container">
    <a href="#">
        <div class="product-item-thumb">
            <img src="<?php echo $this->getSkinUrl($imgPath); ?>?>"/>
        </div>
    </a>
    <div class="product-description" style="clear:both; float:none; height:75px">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ullamcorper venenatis tincidunt.
        Suspendisse ullamcorper blandit sem, eget sollicitudin nisi laoreet at.
        Morbi interdum ipsum nec posuere ornare.
    </div>
</div>