<div class="entry-edit custom-options product-custom-combinations">
    <div id="dynamic-price-warrning" style="display:none">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><?php echo $this->__('Bundle with dynamic pricing cannot include custom defined options. Options will not be saved.') ?></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('catalog')->__('Combination Attributes') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>

    <div id="product_options_container" class="box">
        <div id="product_combinations_container_top"></div>
        <?php echo $this->getCombinationsBoxHtml() ?>
    </div>
</div>
<script type="text/javascript">
    varienWindowOnload(true);
</script>
<style>
    .custom-options .opt-title{
        width:55px;
    }
    .custom-options .opt-type{
        width:150px;
    }
    .custom-options .opt-req{
        width:150px;
    }
</style>