<?php $_menu = $this->getHtml('level-top') ?>
<?php $baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>
<?php
?>
<div class="mobile-nav side-block container">
   <span class="close-sidebar-menu"><i class="icon-cancel"></i></span>
   <div class="menu-all-pages-container">
      <ul class="menu sw-mobile-menu">
          <li class="act">
              <a href="<?php echo $baseUrl ?>customer/account">My Account</a>
              <ul style="display: none">
                  <?php
                  if (Mage::getSingleton('customer/session')->isLoggedIn()) {
                      ?>
                      <li><a href="<?php echo Mage::getUrl('customer/account'); ?>"><?php echo $this->__('Dashboard'); ?></a></li>
                      <li><a href="<?php echo Mage::getUrl('customer/account/logout'); ?>"><?php echo $this->__('Log out'); ?></a></li>
                  <?php } else {
                      ?>
                      <li><a href="<?php echo Mage::getUrl('customer/account/login'); ?>"><?php echo $this->__('Log in'); ?></a></li>
                      <li><a href="<?php echo Mage::getUrl('customer/account/create'); ?>"><?php echo $this->__('Register'); ?></a></li>
                  <?php } ?>
              </ul>
          </li>
        <li class="act"><a href="<?php echo $baseUrl; ?>category/interior-accessories.html">Interior Accessories</a></li>
        <li class="act"><a href="<?php echo $baseUrl; ?>category/exterior-accessories.html">Exterior Accessories</a></li>
        <li class="act"><a href="<?php echo $baseUrl; ?>category/tuneup-and-maintenance-parts.html">Maintenance</a></li>
        <li class="act"><a href="<?php echo $baseUrl; ?>category/subaru-performance-parts.html" style="display: block">Performance</a></li>
        <li class="act"><a href="<?php echo $baseUrl; ?>category/wheels-and-related-accessories.html">Wheels Accessories</a></li>
        <li class="act"><a href="<?php echo $baseUrl; ?>category/cargo-towing-and-racking-accessories.html">Cargo Accessories</a></li>
        <li class="menu-full-width">
              <a href="#">Browse By Model</a>
              <ul class="sw-mobile-menu" style="display: none">
                  <li style="list-style: none;">
                      <a href="/model/subaru-ascent.html">
                          Ascent
                      </a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-baja.html">
                          Baja
                      </a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-brz.html">
                          BRZ
                      </a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-forester.html">
                          Forester
                      </a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-impreza.html">
                          Impreza
                      </a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-legacy.html">
                          Legacy</a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-outback.html">
                          Outback</a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-sti.html">
                          STI</a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-tribeca.html">
                          Tribeca
                      </a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-wrx.html">
                          WRX
                      </a>
                  </li>
                  <li style="list-style: none;">
                      <a href="/model/subaru-xv-crosstrek.html">
                          XV Crosstrek
                      </a>
                  </li>
              </ul>
          </li>
        <li></li>
      </ul>
   </div>
</div>
