    <?php

$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);

$exteriorCategoryId = 369;
$interiorCategoryId = 374;
$maintenanceId = 435;
$moparCategoryId = 434;
$wheelAccessoriesId = 370;
$cargoAccessoriesId = 437;
$catArray = $this->getSubmenuItems();


$interior_accessories = $catArray[$interiorCategoryId];
$exterior_accessories = $catArray[$exteriorCategoryId];
$maintenance_accessories = $catArray[$maintenanceId];
$mopar_accessories =    $catArray[$moparCategoryId];
$wheels_accessories = $catArray[$wheelAccessoriesId];
$cargo_accessories = $catArray[$cargoAccessoriesId];

$helper = Mage::helper('hutility');
?>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 no-padding">
            <div class="header-wrapper">
                <div class="main-nav">
                    <div class="menu-wrapper">
                        <div class="menu-all-pages-container">
                            <ul class="menu main">
                                <li class="menu-full-width with-child <?php echo $helper->hasActiveFitmentQuery() ? 'has-active-ymm':'' ?> open-by-click">
                                    <a href="#">
                                        <div class="anchor-container">Interior Accessories</div><i class="fa fa-caret-down" aria-hidden="true"></i>
                                    </a>
                                    <div class="nav-sublist-dropdown" style="display: none; list-style: none;">
                                        <div class="container">
                                            <div class="mega-columns">
                                                <div class="block1">
                                                    <div class="row" style="margin:0">
                                                        <ul>
                                                            <li class="menu-item col-sm-12" style="list-style: none;">
                                                                <h5><a href="<?php echo $baseUrl; ?>category/interior-accessories.html">Interior Accessories</a></h5>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <?php foreach(array_chunk($interior_accessories, 10) as $interior_accessory): ?>
                                                                        <ul class="col-sm-3 parts-listing">
                                                                            <?php foreach($interior_accessory as $part): ?>
                                                                                <li><a href="<?php echo $baseUrl; ?>part/<?php echo strtolower(str_replace(' ','-',$part)); ?>.html"><?php echo $part; ?></a></li>
                                                                            <?php endforeach; ?>
                                                                        </ul>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <p><br>
                                                                        <a href="<?php echo $baseUrl; ?>category/interior-accessories.html"><b>See More Interior Accessories</b></a>
                                                                    </p>
                                                                </div>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="menu-full-width with-child <?php echo $helper->hasActiveFitmentQuery() ? 'has-active-ymm':'' ?> open-by-click">
                                    <a href="#">
                                        <div class="anchor-container">Exterior Accessories</div><i class="fa fa-caret-down" aria-hidden="true"></i>
                                    </a>
                                    <div class="nav-sublist-dropdown" style="display: none; list-style: none;">
                                        <div class="container">
                                            <div class="mega-columns">
                                                <div class="block1">
                                                    <div class="row" style="margin:0">
                                                        <ul>
                                                            <li class="menu-item col-sm-12" style="list-style: none;">
                                                                <h5><a href="<?php echo $baseUrl; ?>category/exterior-accessories.html">Exterior Accessories</a></h5>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <?php foreach(array_chunk($exterior_accessories, 10) as $exterior_accessory): ?>
                                                                        <ul class="col-sm-3 parts-listing">
                                                                            <?php foreach($exterior_accessory as $part): ?>
                                                                                <li><a href="<?php echo $baseUrl; ?>part/<?php echo strtolower(str_replace(' ','-',$part)); ?>.html"><?php echo $part; ?></a></li>
                                                                            <?php endforeach; ?>
                                                                        </ul>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <p><br>
                                                                        <a href="<?php echo $baseUrl; ?>category/exterior-accessories.html"><b>See More Exterior Accessories</b></a>
                                                                    </p>
                                                                </div>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="menu-full-width with-child <?php echo $helper->hasActiveFitmentQuery() ? 'has-active-ymm':'' ?> open-by-click">
                                    <a href="#">
                                        <div class="anchor-container">Maintenance</div><i class="fa fa-caret-down" aria-hidden="true"></i>
                                    </a>
                                    <div class="nav-sublist-dropdown" style="display: none; list-style: none;">
                                        <div class="container">
                                            <div class="mega-columns">
                                                <div class="block1">
                                                    <div class="row" style="margin:0">
                                                        <ul>
                                                            <li class="menu-item col-sm-12" style="list-style: none;">
                                                                <h5><a href="<?php echo $baseUrl; ?>category/tuneup-and-maintenance-parts.html">Maintenance</a></h5>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <?php foreach(array_chunk($maintenance_accessories, 10) as $maintenance_accessory): ?>
                                                                        <ul class="col-sm-3 parts-listing">
                                                                            <?php foreach($maintenance_accessory as $part): ?>
                                                                                <li><a href="<?php echo $baseUrl; ?>part/<?php echo strtolower(str_replace(' ','-',$part)); ?>.html"><?php echo $part; ?></a></li>
                                                                            <?php endforeach; ?>
                                                                        </ul>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <p><br>
                                                                        <a href="<?php echo $baseUrl; ?>category/tuneup-and-maintenance-parts.html"><b>See More Maintenance</b></a>
                                                                    </p>
                                                                </div>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="menu-full-width with-child <?php echo $helper->hasActiveFitmentQuery() ? 'has-active-ymm':'' ?> open-by-click">
                                    <a href="#">
                                        <div class="anchor-container">Performance</div><i class="fa fa-caret-down" aria-hidden="true"></i>
                                    </a>
                                    <div class="nav-sublist-dropdown" style="display: none; list-style: none;">
                                        <div class="container">
                                            <div class="mega-columns">
                                                <div class="block1">
                                                    <div class="row" style="margin:0">
                                                        <ul>
                                                            <li class="menu-item col-sm-12" style="list-style: none;">
                                                                <h5><a href="<?php echo $baseUrl; ?>category/subaru-performance-parts.html">Performance Parts</a></h5>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <?php foreach(array_chunk($mopar_accessories, 10) as $mopar_accessory): ?>
                                                                        <ul class="col-sm-3 parts-listing">
                                                                            <?php foreach($mopar_accessory as $part): ?>
                                                                                <li><a href="<?php echo $baseUrl; ?>part/<?php echo strtolower(str_replace(' ','-',$part)); ?>.html"><?php echo $part; ?></a></li>
                                                                            <?php endforeach; ?>
                                                                        </ul>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <p><br>
                                                                        <a href="<?php echo $baseUrl; ?>category/subaru-performance-parts.html"><b>See More Performance Parts</b></a>
                                                                    </p>
                                                                </div>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="menu-full-width with-child <?php echo $helper->hasActiveFitmentQuery() ? 'has-active-ymm':'' ?> open-by-click">
                                    <a href="#">
                                        <div class="anchor-container">Wheels Accessories</div><i class="fa fa-caret-down" aria-hidden="true"></i>
                                    </a>
                                    <div class="nav-sublist-dropdown" style="display: none; list-style: none;">
                                        <div class="container">
                                            <div class="mega-columns">
                                                <div class="block1">
                                                    <div class="row" style="margin:0">
                                                        <ul>
                                                            <li class="menu-item col-sm-12" style="list-style: none;">
                                                                <h5><a href="<?php echo $baseUrl; ?>category/wheels-and-related-accessories.html">Wheels Accessories</a></h5>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <?php foreach(array_chunk($wheels_accessories, 6) as $wheels_accessory): ?>
                                                                        <ul class="col-sm-3 parts-listing">
                                                                            <?php foreach($wheels_accessory as $part): ?>
                                                                                <li><a href="<?php echo $baseUrl; ?>part/<?php echo strtolower(str_replace(' ','-',$part)); ?>.html"><?php echo $part; ?></a></li>
                                                                            <?php endforeach; ?>
                                                                        </ul>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <p><br>
                                                                        <a href="<?php echo $baseUrl; ?>category/wheels-and-related-accessories.html"><b>See More Wheels Accessories Parts</b></a>
                                                                    </p>
                                                                </div>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="menu-full-width with-child <?php echo $helper->hasActiveFitmentQuery() ? 'has-active-ymm':'' ?> open-by-click">
                                    <a href="#">
                                        <div class="anchor-container">Cargo Accessories</div><i class="fa fa-caret-down" aria-hidden="true"></i>
                                    </a>
                                    <div class="nav-sublist-dropdown" style="display: none; list-style: none;">
                                        <div class="container">
                                            <div class="mega-columns">
                                                <div class="block1">
                                                    <div class="row" style="margin:0">
                                                        <ul>
                                                            <li class="menu-item col-sm-12" style="list-style: none;">
                                                                <h5><a href="<?php echo $baseUrl; ?>category/cargo-towing-and-racking-accessories.html">Cargo Accessories</a></h5>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <?php foreach(array_chunk($cargo_accessories, 6) as $cargo_accessory): ?>
                                                                        <ul class="col-sm-3 parts-listing">
                                                                            <?php foreach($cargo_accessory as $part): ?>
                                                                                <li><a href="<?php echo $baseUrl; ?>part/<?php echo strtolower(str_replace(' ','-',$part)); ?>.html"><?php echo $part; ?></a></li>
                                                                            <?php endforeach; ?>
                                                                        </ul>
                                                                    <?php endforeach; ?>
                                                                </div>
                                                                <!-- -->
                                                                <div class="col-sm-12">
                                                                    <p><br>
                                                                        <a href="<?php echo $baseUrl; ?>category/cargo-towing-and-racking-accessories.html"><b>See More Cargo Accessories Parts</b></a>
                                                                    </p>
                                                                </div>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <ul class="menu browse-model">
                                <li class="menu-full-width with-child <?php echo $helper->hasActiveFitmentQuery() ? 'has-active-ymm':'' ?> open-by-click">
                                    <a href="#">
                                        <div class="anchor-container">Browse By Model</div><i class="fa fa-caret-down" aria-hidden="true"></i>
                                    </a>
                                    <div class="nav-sublist-dropdown">
                                        <div class="container">
                                            <div class="mega-columns">
                                                <div class="block1">
                                                    <div class="row" style="margin:0">
                                                        <ul>
                                                            <li class="menu-item col-sm-12" style="list-style: none;">
                                                                <h5><a href="<?php echo $baseUrl; ?>make/subaru.html">Browse By Model</a></h5>
                                                                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('megamenu-link-browse-model')->toHtml(); ?>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>