<?php

$collection = $this->getRecommendedProducts();
if(!empty($collection)):
?>
    <div class="popular-products recommended-products">
        <div class="row popular-wrapper">
            <?php foreach ($collection as $product): ?>
                <div class="popular-item col-sm-4 col-xs-12">
                    <div class="image">
                        <a href="<?php echo $product['link'] ?>">
                            <img class="lazyload" data-src="<?php echo $product['image'] ?>" title="<?php echo $product['name'] ?>" alt="<?php echo $product['name'] ?>" />
                        </a>
                    </div>
                    <div class="title">
                        <a href="<?php echo $product['link'] ?>"><?php echo $product['name'] ?></a>
                    </div>
                    <div class="part_name">Part Number: <?php echo $product['part_number'] ?></div>
                    <div class="price"><?php echo $product['price'] ?></div>
                    <div class="small-review"><div class="yotpo bottomLine" data-product-id="<?php echo $product['product_id'] ?>" data-url="<?php echo $product['link'] ?>"></div></div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
