<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 05/11/2018
 * Time: 2:21 PM
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('custom_notice') ?>
        <?php echo $this->getChildHtml('header') ?>
        <?php echo $this->getChildHtml('topContainer'); ?>
        <div class="main-container">
            <?php echo $this->getChildHtml('global_messages') ?>

                    <?php echo $this->getChildHtml('content') ?>

            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
