<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 6/26/17
 * Time: 6:01 PM
 */

$collection = $this->getListing();
$ctr = 0;
$total = $collection->count();
$column=0;
?>
<div id="shop-cat">
    <div class="container">

         <div class="row">
            <div class="col-sm-12">
                <div class="shop-by-category">
                    <h2>
                        <?php if($this->getTitle()):?>
                        <?php echo $this->getTitle(); ?>
                         <?php else: ?>  
                            Shop By Category
                         <?php endif;?> 
                    </h2>
                    <div class="sby-category-listing">
                        <ul class="group-sby-group-listing">
                        <?php foreach($collection as $item): ?>
                            <li>
                                <a href="<?php echo $item->getLink(); ?>">
                                    <?php echo $item->getTitle(); ?>
                                </a>
                            </li>
                    
                        <?php endforeach; ?>
                         </ul>
                    </div>
                </div>                
            </div>

        </div>  

    </div>
</div>


