<?php

$collection = $this->getListing();
$numberOfItem = ceil($collection->count()/ 3);
$begin = true;
$ctr = 1;
?>
<div class="fluid-container lfp-shop-category" id="shop-category">
    <div class="lfp-inner-lg">
        <div class="col-lg-3 col-sm-12">
            <div class="col-sm-8">
                <h2>Shop By Category</h2>
            </div>
        </div>
        <?php foreach($collection as $item): ?>
            <?php if($begin): ?>
                <div class="col-lg-3 col-sm-6 col-xs-12">
            <?php endif;  ?>
            <?php if($item->getIid() != 438):?>
                <a href="<?php echo $item->getLink(); ?>" class="link-item"><span><?php echo $item->getTitle(); ?></span></a><br>
            <?php endif; ?>
            <?php if($ctr % $numberOfItem == 0 || $ctr == $collection->count()): ?>
                <?php $begin = true; ?>
                </div>
            <?php else: ?>
                <?php $begin = false; ?>
            <?php endif; ?>
            <?php
            $ctr++;
        endforeach; ?>
        <div  class="lfp-clear" ></div>
    </div>
</div>
