<?php
$listing = $this->getParts();
$ctr = 0;
$limit = $this->getLimit();
$total = $listing->count();
$title = $this->getTitle();
$titlefix = str_replace(" ","-","$title");
$lowertitle = strtolower($titlefix);

$request = Mage::app()->getRequest();
$requestString = $request->getRequestString();
$requestSegments = array_filter(explode('/', $requestString));
$blockowner = str_replace('.html','',end($requestSegments));
?>
<div class="row">
    <div class="listing-top-text">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing-top-' . $blockowner)->toHtml(); ?>
    </div>
    <div class="part-listing-container">
        <div class="col-sm-12">
            <h3>Choose from these available products:</h3>
            <?php foreach($listing as $item): ?>
                <?php if($ctr % $limit == 0 ): ?>
                    <ul class="col-xs-12 col-sm-3 col-md-3 parts-listing listing-group-<?php echo $ctr+1; ?>">
                <?php endif; ?>
                    <li>
                        <a href="<?php echo $item->getLink(); ?>">
                            <?php echo $item->getLabel(); ?>
                        </a>
                    </li>
                <?php if($ctr % $limit == ($limit - 1) || ($ctr+1) == $total): ?>
                    </ul>
                <?php endif; ?>
                <?php $ctr++; ?>
            <?php endforeach; ?>

        </div>
    </div>
    <div class="listing-bottom-text">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('listing-bottom-' . $blockowner)->toHtml(); ?>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
         jQuery('#shop-cat').detach().insertBefore('.footer-container ');
               
    });
  
</script>