<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 7/4/17
 * Time: 11:29 PM
 */
?>
<div class="row">
<?php echo $this->getChildHtml('product-listing');?>
</div>
<style>
.layered-proxy-container {
    margin-top: 14px;
}
.category-products .block-layered-nav .block-content .content ol li span {
    padding-left: 5px;
    font-weight: normal;
    color: #212121;
    font-family: "Open Sans";
    font-size: 13px!important;
}
</style>