<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 5/13/17
 * Time: 11:51 PM
 */

class Homebase_Autopart_Block_Display_List_Pager extends Mage_Page_Block_Html_Pager{

    /** @var  Mage_Core_Helper_Url $_helper */
    protected $_helper;

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_helper = Mage::helper('core/url');
    }

    private function getCustomRoute(){
        $homeUrl = $this->_helper->getHomeUrl();
        $currentUrl = $this->_helper->getCurrentUrl();
        //Strip home Url
        $stripped_route = str_replace($homeUrl,'', $currentUrl);
        //Clean route of Query strings
        $segment = explode('?', $stripped_route);

        if(is_array($segment)){
            $clean_route = $segment[0];
        }else{
            $clean_route = $stripped_route;
        }
        return $clean_route;
    }

    public function getPagerUrl($params=array())
    {
        $urlParams = array();
        $urlParams['_current']  = true;
        $urlParams['_escape']   = true;
        $urlParams['_use_rewrite']   = true;
        $urlParams['_query']    = $params;
        $urlParams['_direct']   = $this->getCustomRoute();

        return $this->getUrl(null, $urlParams);
    }
}