<?php //echo $this->getChildHtml('sticky.nav') ?>
<?php
$helper = Mage::helper('hutility');
$store = Mage::app()->getStore();
$code  = $store->getCode();
$custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;900&display=swap" rel="stylesheet">
<div class="header-container type6">
    <div class="top-links-container">
        <div class="top-links container">
            <div class="menu-icon"><a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>"><i class="fa fa-bars"></i></a></div>


            <?php
            $store_currency = $this->getChildHtml('store_currency');
            $store_language = $this->getChildHtml('store_language');
            $compare_link = $this->getChildHtml('compare_link');
            ?>
            <?php echo $store_currency; ?>
            <?php if($store_currency && $store_language):?>
            <?php endif; ?>
            <?php //echo $store_language; ?>
            <?php if(($store_currency || $store_language) && $compare_link):?>

            <?php endif; ?>
            <?php echo $compare_link; ?>
            <div class="welcome-text col-sm-8 col-lg-"><?php echo $this->getChildHtml('welcome') ?></div>
            <div class="top-links-area col-sm-4 col-md-12 col-xs-12 col-lg-6">
                <?php echo $this->getChildHtml('minicart'); ?>
                <?php echo $this->getChildHtml('topLinks'); ?>
            </div>
            <div class="clearer"></div>
        </div>
    </div>
    <!-- menu -->
    <div class="menu-container">
        <?php echo $this->getChildHtml('topMenu') ?>
    </div>
    <!-- menu -->
    <div class="header container-fluid">
       <div class="container">
           <!-- LOGO -->
           <div class="row parent-row">
               <div class="col-xs-12 col-sm-12 col-md-4 col-lg-6 logo-container">
                   <?php if ($this->getIsHomePage()):?>
                           <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
                   <?php else:?>
                       <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
                   <?php endif; ?>
               </div>
               <!-- LOGO -->
               <!-- Search -->
               <div class="header-search-box col-xs-12 col-sm-12 col-md-8 col-lg-6">
                   <div class="col-xs-12 col-sm-12">
                       <?php echo $this->getChildHtml('topSearch'); ?>
                   </div>
                   <div class="col-xs-12 megamenu col-sm-4 hide">
                       <div class="header-container-parts-catalog">
                           <div>
                               <span>Replacement Parts Catalog</span>
                               <a href="https://parts.moparoriginamparts.com/" target="_blank">View Parts Here <i class="fa fa-wrench"></i></a>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
           <!-- Search -->
       </div>
    </div>

</div>
<?php echo $this->getChildHtml('mobileMenu') ?>
