<?php //echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<div class="header-container type6">
    <div class="top-links-container">
        <div class="top-links container">
            <div class="top-header-text">
                <div class="black-side"></div>
                <p class="bg-black">All Jeep, Chrysler, Dodge &amp; Ram Parts <span class="text-blue">Discounted up to 30% Off List!</span></p>
            </div>
            <div class="header-search-box">
                <?php echo $this->getChildHtml('topSearch'); ?>
            </div>
            <?php
                $store_currency = $this->getChildHtml('store_currency');
                $store_language = $this->getChildHtml('store_language');
				$compare_link = $this->getChildHtml('compare_link');
            ?>
            <?php echo $store_currency; ?>
            <?php if($store_currency && $store_language):?>
            <?php endif; ?>
            <?php //echo $store_language; ?>
            <?php if(($store_currency || $store_language) && $compare_link):?>
            <span class="split"></span>
            <?php endif; ?>
			<?php echo $compare_link; ?>
            <div class="top-links-area">
                <?php /* <div class="top-links-icon"><a href="javascript:void(0)"><?php echo $this->__("links"); ?></a></div> */ ?>
                <?php 
                echo $this->getChildHtml('minicart');
                echo $this->getChildHtml('topLinks');
                ?>
            </div>
            <!-- <p class="welcome-msg"><?php echo $this->getChildHtml('welcome'); ?> <?php echo $this->getAdditionalHtml(); ?></p> -->
            <div class="clearer"></div>
        </div>
    </div>
    <div class="header container">

        <!-- LOGO -->
        <div class="col-sm-3 logo-container">
            <?php if ($this->getIsHomePage()):?>
                <h1 class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a></h1>
            <?php else:?>
                <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
            <?php endif; ?>
        </div>

        <!-- MAIN MENU -->
        <div class="col-sm-9 menu-container">
            <div class="menu-icon"><a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>"><i class="fa fa-bars"></i></a></div>
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>

        <?php /*
        <!-- SEARCH FIELD -->
        <!-- <div class="col-sm-3"> -->
            <div class="search-area">
                <a href="javascript:void(0)" class="search-icon"><i class="icon-search"></i></a>
                <?php echo $this->getChildHtml('topSearch'); ?>

            </div>
        <!-- </div> --><?php 
        

       <div class="cart-area">
            <?php //echo '<div class="custom-block">'.$this->getLayout()->createBlock('cms/block')->setBlockId($custom_block)->toHtml().'</div>'; ?>
            <?php echo $this->getChildHtml('minicart'); ?>
        </div>
        */ ?>
        <?php //echo $this->getChildHtml("demo_header_tooltip"); ?>
        <div class="header-container-parts-catalog">
            <div>
                <h2>Replacement Parts Catalog</h2>
                <button class="button" title="View Parts Here" onclick="window.open('http://parts.allmoparparts.com/', '_blank')"><span><span>View Parts Here <i class="fa fa-wrench"></i></span></span></button>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('mobile.nav') ?>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function(){
        var scrolled = false;
        jQuery(window).scroll(function(){
            if(200<jQuery(window).scrollTop() && !scrolled){
                jQuery('#slideshow .ymm-form-container').addClass('sticky-header').css('top','-50px').animate({top:'0px'}, 500);
                scrolled = true;
            }
            if(200>jQuery(window).scrollTop() && scrolled){
                jQuery('#slideshow .ymm-form-container').removeClass('sticky-header');
                scrolled = false;
            }
        })
    });
//]]>
</script>