<?php $_menu = $this->getHtml('level-top') ?>
<?php if($_menu): ?>
    <div class="header-wrapper">
        <div class="main-nav">
            <div class="menu-wrapper">
                <div class="menu-all-pages-container">
                    <ul class="menu">
                        <?php echo $_menu ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
