<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 6/28/17
 * Time: 7:09 PM
 */

class Homebase_Auto_Block_Product_Listing_Toolbar extends Mage_Catalog_Block_Product_List_Toolbar{
    /** @var  Mage_Core_Helper_Url $_helper */
    protected $_helper;

    protected function _construct(){
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_helper = Mage::helper('core/url');
    }
    public function getPagerUrl($params=array())
    {
        $urlParams = array();
        $urlParams['_current'] = true;
        $urlParams['_escape'] = true;
        $urlParams['_use_rewrite'] = true;
        $urlParams['_query'] = $params;
        $urlParams['_direct'] = $this->getCustomRoute();

        return $this->getUrl(null, $urlParams);
    }
    private function getCustomRoute(){
        $homeUrl = $this->_helper->getHomeUrl();
        $currentUrl = $this->_helper->getCurrentUrl();
        //Strip home Url
        $stripped_route = str_replace($homeUrl,'', $currentUrl);
        //Clean route of Query strings
        $segment = explode('?', $stripped_route);

        if(is_array($segment)){
            $clean_route = $segment[0];
        }else{
            $clean_route = $stripped_route;
        }
        return $clean_route;
    }
    public function getPagerHtml(){
        $pagerBlock = $this->getLayout()->createBlock('hauto/product_listing_pager');
        if ($pagerBlock instanceof Varien_Object) {

            /* @var $pagerBlock Mage_Page_Block_Html_Pager */
            $pagerBlock->setAvailableLimit($this->getAvailableLimit());

            $pagerBlock->setUseContainer(false)
                ->setShowPerPage(false)
                ->setShowAmounts(false)
                ->setLimitVarName($this->getLimitVarName())
                ->setPageVarName($this->getPageVarName())
                ->setLimit($this->getLimit())
                ->setFrameLength(Mage::getStoreConfig('design/pagination/pagination_frame'))
                ->setJump(Mage::getStoreConfig('design/pagination/pagination_frame_skip'))
                ->setCollection($this->getCollection());

            return $pagerBlock->toHtml();
        }

        return '';
    }
}