<?php
   $_helper = $this->helper('catalog/output');
   $helper_richsnippets = $this->helper('porto/richsnippets');
   $store = Mage::app()->getStore();
   $code  = $store->getCode();
   ?>
<?php $_product = $this->getProduct(); ?>
<?php
   $product = $_product;
   $product_type = $_product->getTypeId();
   $enabled_richsnippets = ($helper_richsnippets->isEnabled() && $product_type !== "grouped");
   $price_properties = "";
   
   if($enabled_richsnippets){
       $price_properties = $helper_richsnippets->getPriceProperties($_product);
   }
   
   $enable_addtocart_sticky = Mage::getStoreConfig("porto_settings/product_view/enable_addtocart_sticky",$code);
   $move_product_tab = Mage::getStoreConfig("porto_settings/product_view/move_product_tab",$code);
   $sticky_header = "";
   if(!Mage::getStoreConfig("porto_settings/header/sticky_header", $code))
       $sticky_header = "no-sticky-header";
   ?>
<?php
$varDataLayer = [
    "name" => $_product->getName(),
    "category" => $_product->getAttributeText('auto_type'),
    "brand" => mage::Helper('growthrocket_gtm')->getDefaultBrand(),
    "id" => $_product->getSku(),
    "price" => Mage::getModel('directory/currency')->format(
        $_product->getFinalPrice(),
        array('display'=>Zend_Currency::NO_SYMBOL),
        false
    ),
    "list" => "Product Details Page",
    "url" => $_product->getProductUrl()
];

?>
<script type="text/javascript">
   var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
   var productDetails = <?php echo json_encode($varDataLayer) ?>;
</script>
<div class="container">
    <div class="row">
        <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
        <div class="product-view <?php if($move_product_tab): ?>moved-tab<?php endif;?>" <?php if($enabled_richsnippets): ?><?php echo $helper_richsnippets->getProductItemscope(); ?><?php endif; ?>>
      <div class="product-essential">
         <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
               <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
               <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <h1 id="product_<?php echo $_product->getId(); ?>" class="product-name" <?php if($enabled_richsnippets): ?>itemprop="name"<?php endif; ?>><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            <!-- PRODUCT MODEL -->
            <div class="row custom-product-detail-container">
               <div id="ymms-product-<?php echo $_product->getId(); ?>" class="ymms-product-name"></div>
               <div class="col-sm-5 no-padding-mobile">
                  <div class="row">
                      <div class="prod-detail-container">
                          Part Number: <span><?php echo $_product->getData('amp_part_number'); ?></span>
                      </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <!-- <div class="product-img-box col-sm-<?php echo Mage::getStoreConfig("porto_settings/product_view/product_image_size", $code); ?> <?php echo Mage::getStoreConfig("porto_settings/product_view/thumbnail_image_type", $code); ?>"> -->
               <div class="product-img-box col-xs-12 col-sm-12 col-md-5">
                   <div class="row">
                       <div class="col-md-12">
                           <?php echo $this->getChildHtml('media') ?>
                       </div>
                       <div class="col-md-2"></div>
                   </div>
               </div>

               <!-- PRODUCT PRICE START  -->
               <div class="col-sm-12 col-xs-12 col-md-7 right-container">
                   <div class="row">
                       <?php echo $this->getChildHtml('compatibilitychecker_view'); ?>
                        <div class="product-info-wrapper">
                       <div class="product-info">

                           <div <?php if($enabled_richsnippets) echo $helper_richsnippets->getOfferItemscope(); ?>>
                               <h2 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
                               <div class="yotpo-pdp-container"> <?php echo $this->helper('yotpo')->showBottomline($this, $_product); ?></div>
                               <?php echo $this->getChildHtml('product_type_data'); ?>
                               <?php echo $this->getTierPriceHtml(); ?>
                               <?php echo $price_properties; ?>
                           </div>
                           <?php echo $this->getChildHtml('extrahint') ?>
                           <?php if ($this->canEmailToFriend()): ?>
                               <!-- <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p> -->
                           <?php endif; ?>
                           <?php if($sku = $_product->getSku()): ?>
                               <?php if($enabled_richsnippets): ?>
                                   <meta itemprop="productID" content="sku:<?php echo $sku; ?>" />
                               <?php endif; ?>
                           <?php endif; ?>
                           <?php echo $this->getChildHtml('alert_urls') ?>
                           <?php echo $this->getChildHtml('other');?>
                       </div>
                       <div class="add-to-box outer-wrapper">
                           <div class="finalprice-label">Final Price</div>
                           <div class="finalprice-value"><?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?></div>
                           <?php if (!$this->hasOptions()):?>
                               <div class="add-to-box">
                                   <?php if($_product->isSaleable()): ?>
                                       <?php echo $this->getChildHtml('addtocart') ?>
                                       <?php //if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                       <?php //endif; ?>
                                   <?php endif; ?>
                                   <?php //echo $this->getChildHtml('addto') ?>
                               </div>
                               <?php echo $this->getChildHtml('extra_buttons') ?>
                           <?php elseif (!$_product->isSaleable()): ?>
                               <div class="add-to-box">
                                   <?php echo $this->getChildHtml('addto') ?>
                               </div>
                           <?php endif; ?>
                           <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                               <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                           <?php endif;?>
                       </div>
                        <div class="clearer"></div>
                   </div>
                       <?php if(!empty($_product->getFreeShippingProduct())): ?>
                           <div class="fs-banner">
                               <span><?php echo $this->__('Free Shipping On This Item') ?></span>
                           </div>
                       <?php endif; ?>

                       <div class="heading">
                           <h3><span>Quick</span> Overview</h3>
                       </div>
                        <div class="product-shop">
                           <?php if($enabled_richsnippets): ?>
                               <?php
                               $storeId = Mage::app()->getStore()->getId();
                               $summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId());
                               ?>
                               <?php if ($summaryData['reviews_count']): ?>
                                   <span itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" class="no-display">
                        <span itemprop="ratingValue"><?php echo $summaryData['rating_summary']; ?></span>
                        <span itemprop="reviewCount"><?php echo $summaryData['reviews_count']; ?></span>
                        <span itemprop="bestRating">100</span>
                        <span itemprop="worstRating">0</span>
                        </span>
                               <?php endif; ?>
                           <?php endif; ?>
                           <?php if ($_product->getDescription()):?>
                               <div class="short-description" style="border:none">
                                   <h2><?php echo $this->__('Quick Overview') ?></h2>
                                   <div class="std" <?php if($enabled_richsnippets): ?>itemprop="description"<?php endif; ?>>
                                       <?php $description = $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>
                                       <?php echo $description; ?>
                                   </div>


                                   <?php
                                   $installationPDF = Mage::helper('instructionpdf')->getInstallationGuidePdf($_product);
                                   if(!empty($installationPDF)){
                                       ?>
                                       <p>  For <?php echo $_product->getData('part_name'); ?> Installation, <a href="<?php echo Mage::helper('instructionpdf')->getGuidePdfUrl($installationPDF); ?>" target="_blank">click here</a></p>
                                       <?php
                                   }
                                   ?>


                               </div>
                           <?php endif;?>
                           <!-- <div class="clearer"></div> -->
                           <?php echo $this->getChildHtml('addthis_sharetool'); ?>
                       </div>
                        <div class="product-collateral col-sm-12">
                           <?php echo $this->getChildHtml('product_additional_data'); ?>
                       </div>
                       <?php echo $this->getChildHtml('upsell_products'); ?>
                       <?php echo $this->helper('yotpo')->showWidget($this, $_product); ?>
                   </div>
               </div>
               <!-- PRODUCT PRICE END  -->
            </div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php //echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
         </form>
         <?php if(Mage::getStoreConfig('ajaxcart/addtocart/enableproduct') && (Mage::app()->getFrontController()->getRequest()->getModuleName() == "catalog") || (Mage::app()->getFrontController()->getRequest()->getModuleName() == "quickview")): ?>
         <script type="text/javascript">
            //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;
            
                        if (url) {
                           form.action = url;
                        }
                        var e = null;
                        if (!url) {
                            url = jQuery('#product_addtocart_form').attr('action');
                        }
                        if(url.indexOf("wishlist/index/cart") != -1){
                            url = url.replace("wishlist/index/cart","ajaxcart/index/add"); // New Code
                        } else {
                            url = url.replace("checkout/cart","ajaxcart/index"); // New Code
                        }
                        url = url.replace("http://", "//");
                        url = url.replace("https://", "//");
                        var data = jQuery('#product_addtocart_form').serialize();
                        data += '&isAjax=1';
                        var is_quickview = false;
                        if(jQuery("body").hasClass("quickview-index-view")){
                            is_quickview = true;
                        }
                        if(is_quickview)
                            window.parent.jQuery("#loading-mask").show();
                        else
                            jQuery('#loading-mask').show();
                        try {
                            jQuery.ajax({
                                url : url,
                                dataType : 'json',
                                type : 'post',
                                data : data,
                                success : function(data) {
                                    if(is_quickview)
                                        window.parent.jQuery('#loading-mask').hide();
                                    else
                                        jQuery('#loading-mask').hide();
                                    if(data.status == 'ERROR'){
                                        if(is_quickview)
                                            window.parent.alert(data.message.replace("<br/>",""));
                                        else
                                            alert(data.message.replace("<br/>",""));
                                    }else{
                                        if(is_quickview){
                                            if(window.parent.jQuery('.header-container .mini-cart')){
                                                window.parent.jQuery('.header-container .mini-cart').replaceWith(data.toplink);
                                            }
                                            if(window.parent.jQuery('.fixed-header .mini-cart')){
                                                window.parent.jQuery('.fixed-header .mini-cart').replaceWith(data.toplink);
                                            }
                                if(window.parent.jQuery('.sticky-header .mini-cart')){
                                    window.parent.jQuery('.sticky-header .mini-cart').replaceWith(data.toplink);
                                }
                                            if(window.parent.jQuery('.col-right .block.block-cart')){
                                                window.parent.jQuery('.col-right .block.block-cart').replaceWith(data.cart_sidebar);
                                            }
                                            window.parent.jQuery('#after-loading-success-message #success-message-container .msg-box').html(data.message);
                                            <?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
                                            ajaxcart_sec = <?php echo ($autoclose && is_numeric($autoclose))?$autoclose:5; ?>;
                                            timer_sec = ajaxcart_sec;
                                            window.parent.jQuery('#after-loading-success-message').fadeIn(200);
                                            ajaxcart_timer = setInterval(function(){
                                                timer_sec --;
                                                window.parent.jQuery('#after-loading-success-message .timer').html(timer_sec);
                                            },1000)
                                            setTimeout(function(){
                                                window.parent.jQuery('#after-loading-success-message').fadeOut(200);
                                                clearTimeout(ajaxcart_timer);
                                                setTimeout(function(){
                                                    window.parent.jQuery('#after-loading-success-message .timer').html(ajaxcart_sec);
                                                }, 1000);
                                            },ajaxcart_sec*1000);
                                        }
                                        else {
                                            if(jQuery('.header-container .mini-cart')){
                                                jQuery('.header-container .mini-cart').replaceWith(data.toplink);
                                            }
                                            if(jQuery('.fixed-header .mini-cart')){
                                                jQuery('.fixed-header .mini-cart').replaceWith(data.toplink);
                                            }
                                if(jQuery('.sticky-header .mini-cart')){
                                    jQuery('.sticky-header .mini-cart').replaceWith(data.toplink);
                                }
                                            if(jQuery('.col-right .block.block-cart')){
                                                jQuery('.col-right .block.block-cart').replaceWith(data.cart_sidebar);
                                            }
                                            jQuery('#after-loading-success-message #success-message-container .msg-box').html(data.message);
                                            <?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
                                            ajaxcart_sec = <?php echo ($autoclose && is_numeric($autoclose))?$autoclose:5; ?>;
                                            timer_sec = ajaxcart_sec;
                                            jQuery('#after-loading-success-message').fadeIn(200);
                                            ajaxcart_timer = setInterval(function(){
                                                timer_sec --;
                                                jQuery('#after-loading-success-message .timer').html(timer_sec);
                                            },1000)
                                            setTimeout(function(){
                                                jQuery('#after-loading-success-message').fadeOut(200);
                                                clearTimeout(ajaxcart_timer);
                                                setTimeout(function(){
                                                    jQuery('#after-loading-success-message .timer').html(ajaxcart_sec);
                                                }, 1000);
                                            },ajaxcart_sec*1000);
                                        }
                                    }
                                }
                            });
                        } catch (e) {
                        }                
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }
                    } else {
                        if(jQuery('#product-options-wrapper'))
                            jQuery('#product-options-wrapper').scrollToMe();
                    }
                }.bind(productAddToCartForm);
            //]]>
         </script>
         <?php else : ?>
         <script type="text/javascript">
            //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;
            
                        if (url) {
                           form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }
            
                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    } else {
                        if(jQuery('#product-options-wrapper'))
                            jQuery('#product-options-wrapper').scrollToMe();
                    }
                }.bind(productAddToCartForm);
                //]]>
                
         </script>
         <?php endif; ?>
         <script type="text/javascript">
            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }
            
                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                } else {
                    if(jQuery('#product-options-wrapper'))
                        jQuery('#product-options-wrapper').scrollToMe();
                }
            }.bind(productAddToCartForm);
         </script>
      </div>
   </div>
    </div>
</div>
<script type="text/javascript">
   jQuery(function($){
       $("body.quickview-index-view .no-rating a, body.quickview-index-view .ratings a").off('click').on("click",function(e){
           window.parent.location.href = $(this).attr("href");
           window.parent.jQuery.fancybox.close();
       });
   <?php
      if($enable_addtocart_sticky){
      ?>
       p_scrolled = false;
       $(window).scroll(function(){
           if(400<$(window).scrollTop() && !p_scrolled){
               $('.sticky-product').removeClass("hide");
               p_scrolled = true;
           }
           if(400>=$(window).scrollTop() && p_scrolled){
               $('.sticky-product').addClass("hide");
               p_scrolled = false;
           }
       });
   <?php
      }
      ?>
   <?php
      if($move_product_tab){
      ?>
       $(".product-info").before($(".product-tabs"));
   <?php
      }
      ?>
   });
</script>
<style>
   .short-description .std > p{
   margin:0;
   line-height: normal;
   }
</style>