<?php
/**
 * Created by PhpStorm.
 * User: ocastro
 * Date: 8/10/17
 * Time: 9:48 PM
 */

class Homebase_Sitemap_Block_Adminhtml_Multimap_Edit extends Mage_Adminhtml_Block_Widget_Form_Container {
    public function __construct(){
        parent::__construct();
        $this->_blockGroup = 'hsitemap';
        $this->_controller = 'adminhtml_multimap';
    }
    public function getHeaderText()
    {
        $this->_headerText = 'Multiple Sitemap';
        return parent::getHeaderText(); // TODO: Change the autogenerated stub
    }
}